langgenius/dify-official-plugins

- tools/vectorizer/provider/vectorizer.yaml
cial API are API Id and API Secret. The original hint was misleading.
> Fix: Modify potentially misleading copy

- tools/slidespeak/manifest.yaml
- tools/slidespeak/provider/slidespeak.py
> fix(slidespeak): miscorrect apikey checking logic

- models/gemini/manifest.yaml
- models/gemini/models/llm/_position.yaml
- models/gemini/models/llm/gemini-2.0-flash-001.yaml
- models/gemini/models/llm/gemini-2.0-flash-exp.yaml
- models/gemini/models/llm/gemini-2.0-flash-lite-preview-02-05.yaml
- models/gemini/models/llm/gemini-2.0-flash-thinking-exp-01-21.yaml
- models/gemini/models/llm/gemini-2.0-flash-thinking-exp-1219.yaml
- models/gemini/models/llm/gemini-2.0-pro-exp-02-05.yaml
- models/gemini/requirements.txt
This PR adds support for new Gemini 2.0 model variants including Flash, Pro, and experimental versions.
- gemini-2.0-flash-001
- gemini-2.0-flash-exp
- gemini-2.0-flash-lite-preview-02-05
- gemini-2.0-pro-exp-02-05
- gemini-2.0-flash-thinking-exp-1219
- gemini-2.0-flash-thinking-exp-01-21
| Model name | Screenshots |
|--------|--------|
| gemini-2.0-flash-001  | <img width="300" alt="flash-001" src="https://github.com/user-attachments/assets/e8a6aad3-506b-4b90-bfce-ba89085584f7" /> |
| gemini-2.0-flash-exp | <img width="300" alt="image" src="https://github.com/user-attachments/assets/2d6b010f-0e0a-4edb-a36c-fbd1bc7a2bd5" /> |
| gemini-2.0-flash-lite-preview-02-05 | <img width="300" alt="image" src="https://github.com/user-attachments/assets/afe39789-afa3-4e14-94c6-821b9bcec60f" /> |
| …
> feat(gemini): add Gemini 2.0 models

- models/deepseek/models/llm/deepseek-chat.yaml
I have updated the pricing of deepseek-chat API as found [here](https://api-docs.deepseek.com/quick_start/pricing)
Fixes #198
> fix: Update deepseek-chat.yaml to include the latest api call prices

- models/vertex_ai/.env.example
- models/vertex_ai/manifest.yaml
- models/vertex_ai/models/llm/gemini-2.0-flash-001.yaml
- models/vertex_ai/models/llm/gemini-2.0-flash-exp.yaml
- models/vertex_ai/models/llm/gemini-2.0-flash-lite-preview-02-05.yaml
- models/vertex_ai/models/llm/gemini-2.0-flash-thinking-exp-01-21.yaml
- models/vertex_ai/models/llm/gemini-2.0-pro-exp-02-05.yaml
- models/vertex_ai/requirements.txt
This PR adds support for new Gemini 2.0 model variants including Flash, Pro, and experimental versions for vertex ai.
- gemini-2.0-flash-001
- gemini-2.0-flash-exp
- gemini-2.0-flash-lite-preview-02-05
- gemini-2.0-pro-exp-02-05
- gemini-2.0-flash-thinking-exp-01-21
| Model name | Screenshots |
|--------|--------|
| gemini-2.0-flash-001  | <img width="300" alt="2_0_flash" src="https://github.com/user-attachments/assets/ef26dbfd-66f9-4942-b8ba-0168ef9d9273" />|
| gemini-2.0-flash-exp |  <img width="300" alt="2_0_exp" src="https://github.com/user-attachments/assets/9293d031-6ba6-4746-81ca-bad81b305dfc" />|
| gemini-2.0-flash-lite-preview-02-05  |<img width="300" alt="2_0_flash_lite_preview" src="https://github.com/user-attachments/assets/e2a4da7f-c14f-4939-9367-9c2fee5dd29e" /> |
| …
> feat(vertex_ai): Support Gemini 2.0 models

- models/bedrock/models/llm/anthropic.claude-3-5-haiku-v1.yaml
- models/bedrock/models/llm/anthropic.claude-3-haiku-v1.yaml
- models/bedrock/models/llm/anthropic.claude-3-opus-v1.yaml
- models/bedrock/models/llm/anthropic.claude-3-sonnet-v1.5.yaml
- models/bedrock/models/llm/anthropic.claude-3-sonnet-v1.yaml
- models/bedrock/models/llm/anthropic.claude-3-sonnet-v2.yaml
- models/bedrock/models/llm/anthropic.claude-instant-v1.yaml
- models/bedrock/models/llm/anthropic.claude-v1.yaml
- models/bedrock/models/llm/anthropic.claude-v2.1.yaml
- models/bedrock/models/llm/anthropic.claude-v2.yaml
- models/bedrock/models/llm/eu.anthropic.claude-3-haiku-v1.yaml
- models/bedrock/models/llm/eu.anthropic.claude-3-sonnet-v1.5.yaml
- models/bedrock/models/llm/eu.anthropic.claude-3-sonnet-v1.yaml
- models/bedrock/models/llm/eu.anthropic.claude-3-sonnet-v2.yaml
- models/bedrock/models/llm/us.anthropic.claude-3-5-haiku-v1.yaml
- models/bedrock/models/llm/us.anthropic.claude-3-haiku-v1.yaml
- models/bedrock/models/llm/us.anthropic.claude-3-opus-v1.yaml
- models/bedrock/models/llm/us.anthropic.claude-3-sonnet-v1.5.yaml
- models/bedrock/models/llm/us.anthropic.claude-3-sonnet-v1.yaml
- models/bedrock/models/llm/us.anthropic.claude-3-sonnet-v2.yaml
The Bedrock Official Plugin was in an uninstallable state. I found that the cause of the error was missing parameters, so this Pull Request fixes the parameters.
- https://github.com/langgenius/dify-official-plugins/issues/141
- https://github.com/langgenius/dify/issues/12625
> 🐛 fix bug by adding missing required parameters for anthropic claude

- tools/siliconflow/tools/janus.py
- tools/siliconflow/tools/janus.yaml
This PR adds support for the Janus Pro 7B model to the SiliconFlow tool. Users can now generate 384x384 resolution images based on text prompts using this model. This model is currently available for free in SiliconFlow.
| Before | After |
|--------|-------|
|  ![image](https://github.com/user-attachments/assets/0895fd75-3f71-47da-b367-9352f17c7f2c)      | ![image](https://github.com/user-attachments/assets/be7fccfc-a80d-4669-8b3b-fec37138f7f7) |
|  None  | ![image](https://github.com/user-attachments/assets/8f961819-6abb-4897-992b-13bb0fe3d003) |
> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.
> feat: add the Janus Pro Model in Siliconflow tool

- models/oci/manifest.yaml
- models/oci/models/llm/_position.yaml
- models/oci/models/llm/cohere.command-r-08-2024.yaml
- models/oci/models/llm/cohere.command-r-16k.yaml
- models/oci/models/llm/cohere.command-r-plus-08-2024.yaml
- models/oci/models/llm/cohere.command-r-plus.yaml
- models/oci/models/llm/llm.py
- models/oci/models/llm/meta.llama-3.1-405b-instruct.yaml
- models/oci/models/llm/meta.llama-3.2-90b-vision-instruct.yaml
- models/oci/models/llm/meta.llama-3.3-70b-instruct.yaml
- models/oci/provider/oci.py
Upgrade oci models, some are depreated and some are added according to latest oracle oci document [About the Chat Models in Generative AI](https://docs.oracle.com/en-us/iaas/Content/generative-ai/chat-models.htm#chat-models).
Deprecated:
- Command R (cohere.command-r-16k) ([Deprecated]
- Command R+ (cohere.command-r-plus) ([Deprecated]
- meta.llama-3-70b-instruct
Added:
- Command R 08-2024 (cohere.command-r-08-2024) (New)
- Command R+ 08-2024 (cohere.command-r-plus-08-2024) (New)
- [Meta Llama 3.3 70B (New)] meta.llama-3.3-70b-instruct
- [Meta Llama 3.2 Family (New)] meta.llama-3.2-90b-vision-instruct
- [Meta Llama 3.1 Family] meta.llama-3.1-405b-instruct
By the way, I've pull a request to original dify repository before (https://github.com/langgenius/dify/pull/13174), but it was merged …
> upgrade oci models [Fix:#288]

- models/openai_api_compatible/manifest.yaml
> chore: bump version of models/openai_api_compatible to 0.0.5

- models/minimax/manifest.yaml
- models/minimax/models/llm/llm.py
- models/minimax/models/llm/minimax-text-01.yaml
* Add new Minimax model "minimax-text-01" to the model_apis dictionary
* Consistent with previous model configuration updates
sync: https://github.com/langgenius/dify/pull/12763
> Add minimax-text-01 model to supported LLM configurations

- models/volcengine_maas/manifest.yaml
- models/volcengine_maas/models/llm/models.py
tool call feature for deepseek v3 is not provided by volcengine ark service
> fix(ark): remove tool call feature for deepseek v3

- models/openai_api_compatible/manifest.yaml
- models/openai_api_compatible/models/rerank/rerank.py
[#14140](https://github.com/langgenius/dify/issues/14140)
rewrite the validate_credentials method of the parent class and add the parameter top_n when calling the _invoke method
> Fix failed to create rerank model when use vllm rerank

- agent-strategies/cot_agent/manifest.yaml
- agent-strategies/cot_agent/strategies/ReAct.py
ReAct Agent instruction param is not used in code
https://github.com/langgenius/dify/issues/14630
> fix: ReAct Agent instruction param is not used

- models/gemini/models/llm/llm.py
Line 326 use time.sleep, but it was never been imported.
It should be well tested before it came to v1.0.0
> fix: missing import `time` module

- tools/gpustack/manifest.yaml
- tools/gpustack/provider/gpustack.py
- tools/gpustack/tools/image_edit.py
- tools/gpustack/tools/image_edit.yaml
- tools/gpustack/tools/text2image.py
- tools/gpustack/tools/text2image.yaml
This PR is going to:
1. Change GPUStack tools API path from `v1-openai` to `v1`
2. Add timeouts for image generation tools, as some LLM-based image generators can take a long time to process requests, potentially causing excessive wait times for users.
> chore: gpustack tools api path

- models/gpustack/README.md
- models/gpustack/manifest.yaml
- models/gpustack/models/llm/llm.py
- models/gpustack/models/rerank/rerank.py
- models/gpustack/models/speech2text/speech2text.py
- models/gpustack/models/text_embedding/text_embedding.py
- models/gpustack/models/tts/tts.py
- models/gpustack/provider/gpustack.yaml
This PR is going to:
- change model API path from `v1-openai` to `v1`
- Add timeout configuration for `rerank` model
- update model plugin docs.
> Update GPUStack model API path

- models/zhipuai/manifest.yaml
- models/zhipuai/models/llm/glm-4v-flash.yaml
- models/zhipuai/models/llm/llm.py
Added GLM-4V-Flash visual model, the current free visual understanding model.
> Updated plugin: zhipuai, added GLM-4V-flash visual understanding model.

- models/azure_openai/manifest.yaml
- models/azure_openai/models/text_embedding/text_embedding.py
Modifies the get_num_tokens  function in text_embedding model to return the correct data type
Fix https://github.com/langgenius/dify/issues/14656
> Fixes get_num_tokens function to return []int instead of int

- models/azure_openai/manifest.yaml
- models/azure_openai/models/constants.py
- models/azure_openai/models/llm/llm.py
- models/azure_openai/provider/azure_openai.yaml
- models/azure_openai/requirements.txt
This PR changes following:
- ✅ Add the latest API version; `2025-01-01-preview`
- ✅ Correct price table for `o1-mini`
- https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/
- $1.10 for Input and $4.40 for Output, instead of $3.00 for Input and $12.00 for Outpu
- ✅ Correct context window for `o3-mini`
- https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/reasoning
- 200,000 for Input and 100,000 for Output, instead of 128,000 for Input and 65,535 for Output
- ✅ Add support of Function Calling for `o3-mini`
- ✅ Add new base model; `o1`
- ✅ Add parameter `reasoning_effort` for `o3-mini`
Closes #404, closes #408
I understand that multiple topics should not be mixed in a single PR, sorry for this, but since these were many small fixes, I have …
> feat(azure_openai): add o1 base model, support reasoning_effort, and fix minor issues

- models/cohere/manifest.yaml
- models/cohere/models/rerank/_position.yaml
- models/cohere/models/rerank/rerank-multilingual-v2.0.yaml
- models/cohere/models/rerank/rerank-v3.5.yaml
- models/cohere/provider/cohere.py
1. rerank-v3.5 was missing, so it was added.
2. removed rerank-english-v2.0 and rerank-multilingual-v2.0 as they were deprecated
- PR with the addition of Rerank v3.5
https://github.com/langgenius/dify/issues/11347
- Rerank v2.0 related issues
https://github.com/langgenius/dify/issues/14284
- bug report
https://github.com/langgenius/dify/issues/15333
> modified rerank model of cohere

- models/vertex_ai/manifest.yaml
- models/vertex_ai/models/llm/llm.py
- models/vertex_ai/models/text_embedding/text_embedding.py
When I leave blank `Service Account Key` field to use ADC(Application Default Credential), got error "vertex_service_account_key"
To fix this issue, set service_account_info as None when vertex_service_account_key param is not set.
> set service_account_info as None when vertex_service_account_key param is not set

- models/bedrock/manifest.yaml
- models/bedrock/models/llm/amazon.nova-lite-v1.yaml
- models/bedrock/models/llm/amazon.nova-micro-v1.yaml
- models/bedrock/models/llm/amazon.nova-pro-v1.yaml
- models/bedrock/models/llm/us.amazon.nova-lite-v1.yaml
- models/bedrock/models/llm/us.amazon.nova-micro-v1.yaml
- models/bedrock/models/llm/us.amazon.nova-pro-v1.yaml
In `top_p` descriptions, fixed `Anthropic Claude` to `Amazon Nova`.
> docs: Update top_p descriptions for Amazon Nova models

- tools/jina/manifest.yaml
- tools/jina/tools/jina_reader.py
- tools/jina/tools/jina_reader.yaml
Now when we use the jina_reader tool, we can choose whether to remove the images in the parsing results and whether to allow the Jina server to cache the web pages we parse.
> feat(jina_reader): add options to remove images and control caching behavior

- models/novita/manifest.yaml
Reason: The plugin version number was updated to 0.0.3 because the previous contributor made changes to the plugin but forgot to upgrade its version. This oversight caused installations to still use the outdated content.
> fix(novita model): revised version number to 0.0.3 and remove duplicate description

- extensions/oaicompat_dify_model/endpoints/llm.py
- extensions/oaicompat_dify_model/manifest.yaml
now, the request error message
```
{
"code": -500,
"message": "{"message":"{\"args\":{},\"error_type\":\"TypeError\",\"message\":\"dify_plugin.entities.model.llm.LLMModelConfig() got multiple values for keyword argument 'completion_params'\"}","error_type":"PluginDaemonInternalServerError","args":null}",
"data": null
}
``
close #452
> fix：LLMModelConfig() got multiple values for keyword argument 'comple

- models/openai_api_compatible/manifest.yaml
- models/openai_api_compatible/models/rerank/rerank.py
add missing import of CredentialsValidateFailedError for openai-compatible plugin
> Fix missing import in rerank.py for openai-compatible plugin

- models/bedrock/models/llm/llm.py
- Updated reasoning content formatting to use opening and closing tags for the first block.
- Simplified subsequent block handling by removing unnecessary tags.
- Ensured proper closing of reasoning tags when content blocks are processed.
- Maintained code consistency by updating full assistant content handling.
> Refactor reasoning content formatting in BedrockLargeLanguageModel

- models/gpustack/manifest.yaml
- models/gpustack/models/speech2text/speech2text.py
https://github.com/langgenius/dify-official-plugins/pull/447#issuecomment-2724317646
Fix missing custom model schema for GPUStack Speech2text
Fix https://github.com/langgenius/dify/issues/15911
> fix: gpustack speech to text schema

- models/anthropic/manifest.yaml
- models/anthropic/models/llm/llm.py
Fixes: https://github.com/langgenius/dify/issues/16082
The message history should maintain:
Assistant message with tool_use
User message with tool_result
But instead it's creating:
Assistant message with thinking + tool_use + text (duplicating the content)
User message with tool_result
> Fix anthropic thinking mode with tool use chat history arrangement

- models/vertex_ai/manifest.yaml
- models/vertex_ai/models/llm/llm.py
- models/vertex_ai/requirements.txt
When running with the Grounding option enabled in the Vertex AI plugin for Gemini 1.5 and other models, it fails because the DynamicRetrievalConfig object does not exist.
The library installed in [requirements.txt](https://github.com/langgenius/dify-official-plugins/blob/main/models/vertex_ai/requirements.txt) is version 1.71.1, but the latest Google SDK is 1.85.0.
- The latest version of [vertexai](https://pypi.org/project/vertexai/) is 1.71.1 and has stopped being updated.
- [Google SDK](https://pypi.org/project/google-cloud-aiplatform/) supports up to version 1.85.0.
DynamicRetrievalConfig is not implemented in version 1.71.1, causing the failure, but updating to version 1.85.0 will resolve this issue.
- Selfhost
- Dify v1.0
- Plugin(Vertex AI | Google Cloud Platform) v0.0.7
> VertexAI Models: replace vertexai library into google-cloud-aiplatform

- models/tongyi/manifest.yaml
- models/tongyi/models/llm/llm.py
- models/tongyi/requirements.txt
Fix #424 
When stream = true and incremental_output = true, the tool call will report an error, when stream-tool-call incremental_output must be false
> fix:Failed to transform agent message using tongyi function calling

- tools/github/manifest.yaml
- tools/github/provider/github.yaml
- tools/github/requirements.txt
- tools/github/tools/github_repository_readme.py
- tools/github/tools/github_repository_readme.yaml
New feature: Retrieve the content of a README file from a GitHub repository.
github api: https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-a-repository-readme
> feat: add GitHub repository README tool for github plugin

- models/azure_openai/manifest.yaml
- models/azure_openai/models/llm/llm.py
- models/azure_openai/requirements.txt
This PR changes following implementations:
- ✅ Changed the conditional `if` statement based on the model name to a judgment using `base_model_name`
- In AOAI, the model name can be changed arbitrarily by the user, making it impossible to predict precisely; however, base_model_name can be predicted.
- ✅ If the model supports tool calls, but doesn't support straming, there are cases where an empty array `[]` is returned as the  content from LLM in models, which was causing errors on the API side. To resolve this, This PR changed it to return `""` when the result is `[]`.
- ✅ The model o3-mini supports streaming, but it was forced to `stream: false` Corrected conditionals for this.
closes #487
> fix(azure_openai): support streaming for o3 based models

- tools/github/manifest.yaml
- tools/github/tools/github_repository_readme.py
Why modify the error handling logic of this tool? 
When retrying on failure is enabled, the retry will not be executed because the system does not capture the error.
After modification, retry is allowed.
> fix: improve error handling in GitHub README tool

- models/azure_openai/manifest.yaml
- models/azure_openai/models/constants.py
- models/azure_openai/models/llm/llm.py
This PR makes `response_format: "json_schema"` work correctly through the following changes:
- ✅ Override `_code_block_mode_wrapper` to skip it if `response_format` is NOT `JSON` or `XML`
- The fundamental fix is here: https://github.com/langgenius/dify-plugin-sdks/pull/57
- This is a temporary workaround before merging langgenius/dify-plugin-sdks#57
- ✅ Update parameter rules for each models
- The latest `gpt-4o` and `gpt-4o-mini` supports `json_schema`, so I added it
- `o1-mini` and `o1-preview` do not support `response_format` and `json_schema`, so I removed it ([refer to the official doc](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/reasoning#api--feature-support))
- ✅ Bump plugin version from 0.0.8 to **0.0.10**
- I've already bump its version to **0.0.9** in …
> fix(azure_openai): add workaround to json_schema mode before fundamental fix will be merged

- tools/dingtalk/manifest.yaml
- tools/dingtalk/provider/dingtalk.yaml
- tools/dingtalk/requirements.txt
- tools/dingtalk/tools/dingtalk_group_bot.py
- tools/dingtalk/tools/dingtalk_group_bot.yaml
feat(dingtalk): 支持 Markdown 消息类型并优化工具配置
- 在钉钉群机器人工具中添加了对 Markdown 消息类型的支持
- 更新了工具配置，增加了消息类型选择参数- 调整了 payload构造逻辑，根据消息类型选择合适的格式
- 更新了工具和插件的版本号
- 更新dify插件版本号至=0.0.1b74
> Feat dingtalk message type

- tools/bing/manifest.yaml
- tools/bing/provider/bing.py
Fixes #553 
BingSearch uses user-selected fields([Bing Search FEATURES](https://www.microsoft.com/en-us/bing/apis/pricing)) for authorization.
> fix: BingSearch credential validations

- models/azure_openai/manifest.yaml
- models/azure_openai/requirements.txt
The SDK version 0.0.1b74 causes following issues:
- https://github.com/langgenius/dify/issues/16353
- https://github.com/langgenius/dify/issues/16726
- https://github.com/langgenius/dify/issues/16816
This PR pins the SDK version to 0.0.1b73 as a temporary workaround.
- For openai: https://github.com/langgenius/dify-official-plugins/pull/569
- For azure_openai: https://github.com/langgenius/dify-official-plugins/pull/568
- For openrouter: https://github.com/langgenius/dify-official-plugins/pull/572
> fix(azure_openai): temporarily pin sdk version

- models/openrouter/manifest.yaml
- models/openrouter/requirements.txt
The SDK version 0.0.1b74 causes following issues:
- https://github.com/langgenius/dify/issues/16353
- https://github.com/langgenius/dify/issues/16726
- https://github.com/langgenius/dify/issues/16816
This PR pins the SDK version to 0.0.1b73 as a temporary workaround.
- For openai: https://github.com/langgenius/dify-official-plugins/pull/569
- For azure_openai: https://github.com/langgenius/dify-official-plugins/pull/568
- For openrouter: https://github.com/langgenius/dify-official-plugins/pull/572
> fix(openrouter): temporarily pin sdk version

- models/openai/manifest.yaml
- models/openai/requirements.txt
The SDK version 0.0.1b74 causes following issues:
- https://github.com/langgenius/dify/issues/16353
- https://github.com/langgenius/dify/issues/16726
- https://github.com/langgenius/dify/issues/16816
This PR pins the SDK version to 0.0.1b73 as a temporary workaround.
- For openai: https://github.com/langgenius/dify-official-plugins/pull/569
- For azure_openai: https://github.com/langgenius/dify-official-plugins/pull/568
- For openrouter: https://github.com/langgenius/dify-official-plugins/pull/572
> fix(openai): temporarily pin sdk version

- agent-strategies/cot_agent/manifest.yaml
- agent-strategies/cot_agent/strategies/function_calling.py
The function-calling agent redundantly inserts system and user prompts into message history every iteration.
> [!IMPORTANT]
> At least one environment must be tested.
Local Deployment Dify Version: 1.1.3
> fix: Redundant insertion of system/user prompts in the function-calling agent

- models/huggingface_hub/manifest.yaml
- models/huggingface_hub/models/text_embedding/text_embedding.py
This addresses the issue #660.
`dify_plugin.errors.model.InvokeError: [models] Error: 2 validation errors for EmbeddingUsage
tokens
Input should be a valid integer [type=int_type, input_value=[82], input_type=list]
For further information visit https://errors.pydantic.dev/2.8/v/int_type
total_tokens
Input should be a valid integer [type=int_type, input_value=[82], input_type=list]`
used `tokens[0]` instead of `tokens`
> fix: PluginInvokeError with Hugging Face in Dify: Pydantic Validation Error (EmbeddingUsage expects integer instead of list)

- models/volcengine_maas/manifest.yaml
- models/volcengine_maas/models/llm/models.py
volcengine deepseek-v3-250324 support 128k context and 16k max token output
deepseek-r1 support 16k max token output
[volcengine doc](https://www.volcengine.com/docs/82379/1330310#deepseek)
> Update volcengine deepseek v3 r1 max_token & context_size

- models/bedrock/manifest.yaml
- models/bedrock/models/llm/llm.py
> fix bedrock converse

- models/openrouter/manifest.yaml
- models/openrouter/models/llm/_position.yaml
- models/openrouter/models/llm/claude-3.7-sonnet.yaml
This Pull Request adds Claude-3.7-sonnet model as a default option to Dify's OpenRouter plugin. The goal is to improve API provider consolidation and enhance access to the latest models.
> Added Claude-3.7-sonnet model to openrouter plugin

- models/vertex_ai/manifest.yaml
- models/vertex_ai/models/llm/gemini-2.5-flash-preview-04-17.yaml
- models/vertex_ai/models/llm/gemini-2.5-pro-preview-03-25.yaml
- models/vertex_ai/models/llm/llm.py
- models/vertex_ai/requirements.txt
Fixed this error, which was raised when using the openai style output schema JSON (like "type": ["string", "null"]), which is not supported by Gemini.
`[vertex_ai] Error: PluginInvokeError: {"args":{"description":"[models] Error: 'list' object has no attribute 'upper'"},"error_type":"InvokeError","message":"[models] Error: 'list' object has no attribute 'upper'"}`
Also bnd bumped up to `dify_plugin>=0.2.0,<0.3.0`
> fix/Fixed output structure error in Vertex ai

- models/gpustack/manifest.yaml
- models/gpustack/models/rerank/rerank.py
When users configure the rerank model using GPUStack plugins, they often mistakenly paste a URL that already includes `/v1/`. Our system automatically appends `/v1/rerank`, which leads to an error due to the duplicated path (`/v1/v1/rerank`). We need to make this configuration process **foolproof**, so users can simply paste their base URL without worrying about whether `/v1/` is included, ensuring it works correctly either way.
> chore: optimize the gpustack rerank path

- models/llama_api/manifest.yaml
- models/llama_api/models/llm/llm.py
- models/llama_api/requirements.txt
https://github.com/langgenius/dify-official-plugins/pull/845 introduced Llama API plugin.
Initially we are using transformers package to count tokens, but somehow the production version of dify has this weird error
```
[llama-api] Error: PluginInvokeError: {"args":{},"error_type":"KeyError","message":"\u003cclass 'transformers.models.bit.configuration_bit.BitConfig'\u003e"}
```
I suspect it's related to some transformers package dependencies version incompatibility or something.
Upon digging futher, looks like dify provide a util function to count an approximate tokens using _get_num_tokens_by_gpt2()
I saw many model providers are using that too, and hence migrating to that and removing transformers as a package dependencies.
I tested this by building the dify plugin manually, and upload …
> Remove transformers dependencies on Llama API plugin

- models/bedrock/README.md
- models/bedrock/main.py
- models/bedrock/manifest.yaml
- models/bedrock/models/llm/llm.py
> fix: bedrock validate_credentials problem (0.0.16)

- models/azure_openai/manifest.yaml
- models/azure_openai/models/constants.py
> feat[azure_openai]: add vision support for o-series models

- models/vertex_ai/main.py
- models/vertex_ai/manifest.yaml
- models/vertex_ai/models/llm/llm.py
- models/vertex_ai/models/text_embedding/text_embedding.py
This PR fixes an issue where the Vertex AI plugin hangs during document ingestion when handling multiple tasks. The problem was caused by gRPC transport not working well with the Gevent-based runtime. Switching to REST transport solves the issue.
Root Cause: gRPC transport hangs under concurrency due to incompatibility with Gevent.
Fix: Use REST transport in the Vertex AI SDK.
- Why did the Dify plugin daemon get stuck?
It was waiting for responses from the Python plugin runtime, which never completed the embedding tasks.
- Why were the tasks never completed?
The Python plugin runtime got stuck during the first call to Vertex AI SDK’s embedding method.
- Why did it get stuck on that call?
The SDK used gRPC, which isn’t compatible with the Gevent/greenlets concurrency model.
- Why was gRPC …
> fix(vertex-ai): switch to REST transport to fix concurrency hang

- models/openrouter/manifest.yaml
- models/openrouter/models/llm/llm.py
The OpenRouter API returns reasoning content in the "reasoning" field instead of "reasoning_content". So we need to override the `_wrap_thinking_by_reasoning_content` method to support the reasoning content from OpenRouter.
> Support reasoning content from OpenRouter

- models/anthropic/README.md
- models/anthropic/main.py
- models/anthropic/manifest.yaml
- models/anthropic/models/llm/claude-3-5-haiku-20241022.yaml
- models/anthropic/models/llm/claude-3-5-sonnet-20240620.yaml
- models/anthropic/models/llm/claude-3-5-sonnet-20241022.yaml
- models/anthropic/models/llm/claude-3-7-sonnet-20250219.yaml
- models/anthropic/models/llm/claude-opus-4-20250514.yaml
- models/anthropic/models/llm/claude-sonnet-4-20250514.yaml
- models/anthropic/models/llm/llm.py
- models/anthropic/requirements.txt
Also handle multi-modal contents in best practice.
https://docs.anthropic.com/en/docs/build-with-claude/pdf-support#:~:text=Send%20your%20first%20PDF%20request
https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching
> refract: anthropic claude prompt caching

- tools/gpustack/manifest.yaml
- tools/gpustack/provider/gpustack.py
- tools/gpustack/tools/utils.py
When user configure GPUStack image tool, it will very easily add path `/v1` or `/v1-openai` to the server url, which will cause 404 not found, as the image tool in 0.2 will append v1. We want fix it by removing additional /v1 or /v1-openai. 
As the screenshots shows, the tool plugins could config /v1 or /v1-openai path.
> fix: gpustack image tool compatible url path

- models/openai/manifest.yaml
- models/openai/models/llm/gpt-5-chat-latest.yaml
- models/openai/models/llm/llm.py
Adjusted context_size and max_tokens in gpt-5-chat-latest.yaml based on API testing and documentation. Added comments to clarify discrepancies between documentation and actual API limits.
> Fix(openai): tool use issue with latest openai SDK, gpt 5 chat latest might contains incorrect context window size

- models/gemini/manifest.yaml
- models/gemini/models/llm/llm.py
- models/gemini/pyproject.toml
- models/gemini/requirements.txt
Related: #1360
This PR introduces a solution to fully resolve token counting issues for `prompt_tokens` and `completion_tokens` in **multi-modal QA** scenarios using the Gemini GenAI SDK.
---
* **Problem**:
In the Gemini GenAI SDK, token statistics for `prompt_tokens` and `completion_tokens` were previously inaccurate in multi-modal QA scenarios, leading to inconsistencies in total token usage reporting.
* **Fix**:
Implemented a solution that ensures:
* `total_token_count` is always consistent.
* Correct pricing is applied for the following modalities: **IMAGE**, **VIDEO**, **TEXT**, and **DOCUMENT**.
* **Limitations**:
Due to current constraints in Dify:
* Different modalities cannot be assigned distinct token prices.
* The system does not track tiered (step-wise) pricing.
* As a result, …
> fix(gemini): usage metadata

- models/zhipuai/manifest.yaml
- models/zhipuai/models/llm/llm.py
close: https://github.com/langgenius/dify-official-plugins/issues/1397
> feat: zhipuai support thinking

- models/gemini/manifest.yaml
- models/gemini/models/llm/gemini-1.5-flash-001.yaml
- models/gemini/models/llm/gemini-1.5-flash-8b-exp-0827.yaml
- models/gemini/models/llm/gemini-1.5-flash-8b-exp-0924.yaml
- models/gemini/models/llm/gemini-1.5-flash-exp-0827.yaml
- models/gemini/models/llm/gemini-1.5-flash-latest.yaml
- models/gemini/models/llm/gemini-1.5-pro-001.yaml
- models/gemini/models/llm/gemini-1.5-pro-exp-0801.yaml
- models/gemini/models/llm/gemini-1.5-pro-exp-0827.yaml
- models/gemini/models/llm/gemini-2.0-pro-exp-02-05.yaml
- models/gemini/models/llm/gemini-2.0-pro-exp.yaml
- models/gemini/models/llm/gemini-2.5-flash-preview-04-17.yaml
- models/gemini/models/llm/gemini-2.5-pro-exp-03-25.yaml
- models/gemini/models/llm/gemini-exp-1114.yaml
- models/gemini/models/llm/gemini-exp-1121.yaml
- models/gemini/models/llm/gemini-exp-1206.yaml
- models/gemini/models/llm/learnlm-1.5-pro-experimental.yaml
- models/gemini/models/llm/llm.py
- models/gemini/provider/google.py
- models/gemini/pyproject.toml
This PR improves the handling of Gemini model configurations and cleans up the model list.
**Key Changes:**
*   **Deprecations:**
*   Added `deprecated: true` to several experimental and legacy Gemini models in their YAML configs.
*   **Refactoring ( `GoogleLargeLanguageModel` ):**
*   Fix: Introduced a temporary blacklist to prevent errors when setting `thinking_config` on incompatible models (e.g., `gemini-2.0-flash-preview-image-generation`, `nano-banana`). This is a short-term fix.
*   Feature: Configured correct response modalities for models with mixed-mode outputs (image, audio).
*   Refactoring: Extracted chat parameter and tool calling logic into dedicated methods (`_set_chat_parameters`, `_set_tool_calling`) to improve code organization.
*   Goal: The overall refactor makes …
> fix(gemini-config): deprecate multiple gemini models and refine thinking/response modality config

- models/openai_api_compatible/manifest.yaml
- models/openai_api_compatible/models/llm/llm.py
This PR fixes structured output for the OpenAI-API-Compatible plugin as outlined in [issue 1568](https://github.com/langgenius/dify-official-plugins/issues/1568). The bug is changing the response format from json_schema to json_object while also passing the json_schema. This causes an error when used with OpenAI and LiteLLM. The fix simply removes the change from json_schema to json_object.
Before change:
After change:
> Fix structured output error using OpenAI api compatible #1568

- models/volcengine_maas/manifest.yaml
- models/volcengine_maas/models/client.py
- models/volcengine_maas/models/llm/llm.py
- models/volcengine_maas/models/llm/models.py
- [x ] I have Ensured `dify_plugin>=0.3.0,<0.5.0` is in requirements.txt ([SDK docs](https://github.com/langgenius/dify-plugin-sdks/blob/main/python/README.md))
> feat: add response format support for structured output in volcengine models (doubao-seed-1.6)

- tools/general_chunk/manifest.yaml
- tools/general_chunk/requirements.txt
- tools/parent_child_chunk/manifest.yaml
- tools/parent_child_chunk/requirements.txt
- tools/qa_chunk/manifest.yaml
- tools/qa_chunk/requirements.txt
NOTE: This is intended for the ✨ **feat/datasource** branch, not for **main**.
New `$ref: "https://..."` format does not work with old SDK version.
This PR bumps SDK version for the plugin which has new ref format and uses old SDK version.
Follow-up for: https://github.com/langgenius/dify-official-plugins/commit/4a3f0478c8c224114e9f2937fd048bed2bacffb9
```bash
2025/08/28 13:44:59 run.go:135: [ERROR]plugin langgenius/general_chunker:0.0.2 exited with error: exit status 1
luginRegistration(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/cwd/langgenius/general_chunker-0.0.2@8c2f309e9d67a472dad1e9d1e8d1de89249859551b60682f545c7c5ba6bb344a/.venv/lib/python3.12/site-packages/dify_plugin/core/plugin_registration.py", line 127, in __init__
self._load_plugin_configuration()
File …
```
> fix(feat/datasource): bump sdk version to support new ref format for output schema

- models/bedrock/manifest.yaml
- models/bedrock/models/llm/llm.py
- Link Related Issues if Applicable: [#1400](https://github.com/langgenius/dify-official-plugins/issues/1400)
This error occurs sporadically - sometimes the same model configuration works, sometimes it fails.
The issue is in the `_get_model_info` method where `model_parameters.pop('model_name')` removes the `model_name` parameter from the dictionary. When the Converse API call fails and the code falls back to the traditional API, the fallback logic tries to retrieve `model_name` using `model_parameters.get('model_name')`, but the parameter has already been removed by the previous `pop()` operation.
**Flow that causes the error:**
1. `_get_model_info()` is called with `model_parameters` containing `model_name`
2. Line 282: `model_name = model_parameters.pop('model_name')` - **removes** …
> fix: bedrock provider "Model name is required for non-converse API models" error

- tools/parent_child_chunk/manifest.yaml
- tools/parent_child_chunk/tools/parent_child_chunk.yaml
> alert subchunk_separator default to "\n"

- tools/dify_extractor/manifest.yaml
- tools/dify_extractor/provider/dify_extractor.yaml
- tools/general_chunk/manifest.yaml
- tools/general_chunk/provider/general_chunk.yaml
- tools/parent_child_chunk/manifest.yaml
- tools/parent_child_chunk/provider/parent_child_chunk.yaml
- tools/qa_chunk/manifest.yaml
- tools/qa_chunk/provider/qa_chunk.yaml
- tools/unstructured/manifest.yaml
- tools/unstructured/provider/unstructured.yaml
The `rag` tag is not supported by current frontend code. Remove it
to avoid breaking existing Dify deployments.
The `minimum_dify_version` field is raised to `2.0.0-beta1` to ensure
users of old version get proper compatibility notice while trying to
install those plugins.
NO
> fix: Remove `rag` tag for Knowledge Pipeline related plugins, bump `minimum_dify_version`

- models/xinference/manifest.yaml
- models/xinference/models/text_embedding/text_embedding.py
- fixes: #1713
- Added support for the `task=retrieval` parameter when using `jina-embeddings-v4` model
- This ensures proper embedding generation for retrieval tasks
- Maintains backward compatibility for other models
> feat(xinference): add task parameter for jina-embeddings-v4 model

- tools/mineru/manifest.yaml
- tools/mineru/tools/parse.py
- tools/mineru/tools/parse.yaml
update: backend option description
update: sglang_server_url -> server_url simplified
update: bump version to 0.5.0
> feat(mineru): add backend options for mineru2.5

- tools/confluence/manifest.yaml
- tools/confluence/provider/confluence.yaml
This PR completes the fix for Confluence plugin authentication that was partially addressed in PR #1392.
- Fixes #1372 (Add dropdown to ask for Basic vs PAT token)
- Closes #1807 (token_type selector missing in UI)
- Related to PR #1392 (Added backend support but missing UI field)
Issue #1372 requested a dropdown to select between Basic and Bearer token types. PR #1392 partially fixed this by updating `auth.py` to read the `token_type` parameter, but the UI field in
`confluence.yaml` was never added. This means:
- Confluence Cloud users cannot use the plugin (requires Basic auth)
- Users must manually understand and prefix tokens with "Bearer " or "Basic "
- The `token_type` parameter always defaults to 'Bearer' with no way to change it
This PR adds the missing UI component to complete …
> fix(confluence): Add token_type selector for Cloud/Server auth support
