langgenius/dify-official-plugins

models/gpustack/manifest.yaml
models/gpustack/models/llm/llm.py
models/gpustack/models/speech2text/speech2text.py
models/gpustack/models/tts/tts.py
models/gpustack/provider/gpustack.yaml

Support tts and speech2text for gpustack. Request by https://github.com/langgenius/dify/pull/12381#issuecomment-2574234066

feat: add tts and speech2text model for gpustack

---

models/siliconflow/manifest.yaml
models/siliconflow/provider/siliconflow.py

fix: siliconflow-validate-credentials

---

tools/duckduckgo/manifest.yaml
tools/duckduckgo/requirements.txt

fix duckduckgo search not work

---

models/deepseek/manifest.yaml
models/deepseek/models/llm/deepseek-chat.yaml

fix https://github.com/langgenius/dify/issues/12621

fix deepseek chat misalign

---

agent-strategies/cot_agent/manifest.yaml
agent-strategies/cot_agent/requirements.txt
agent-strategies/cot_agent/strategies/ReAct.py
agent-strategies/cot_agent/strategies/function_calling.py

Agent node support stream output

bump: cot_agent to 0.0.5

---

tools/slack/manifest.yaml
tools/slack/provider/slack.py

fix(slack): bad provider init logic

---

models/azure_ai_studio/manifest.yaml
models/azure_ai_studio/models/llm/llm.py
models/azure_ai_studio/requirements.txt

sync: https://github.com/langgenius/dify/pull/13267/files

feat: support deepseek r1 for azure-ai-foundry

---

tools/perplexity/tools/perplexity_search.py
tools/perplexity/tools/perplexity_search.yaml

Same modification as https://github.com/langgenius/dify/pull/13694
Close #209

Add new models for built-in Perplexity Tool

---

tools/comfyui/manifest.yaml
tools/comfyui/provider/comfyui.py
tools/comfyui/tools/comfyui_client.py

Default consider comfyui deploy in local with ws:// prefix, add supported for wss://

fix comfyui for wss connection

---

models/x/manifest.yaml
models/x/models/llm/grok-2-1212.yaml
models/x/models/llm/grok-2-vision-1212.yaml
models/x/models/llm/grok-beta.yaml
models/x/provider/x.yaml

* Add predefined LLM models configuration
* Bump provider version to 0.0.3

feat: update xAI provider configuration and manifest version

---

models/openai/manifest.yaml
models/openai/models/llm/llm.py

- Add support for JSON schema response format
- Validate and parse JSON schema when specified
- Improve response format parameter processing
- Bump plugin version to 0.0.8

feat: enhance OpenAI model response format handling

---

extensions/openai_compatible/manifest.yaml
models/openai_api_compatible/provider/openai_api_compatible.yaml

see [plugin sdk PR](https://github.com/langgenius/dify-plugin-sdks/pull/24)

add endpoint model name

---

models/localai/manifest.yaml
models/localai/models/text_embedding/text_embedding.py

Related to https://github.com/langgenius/dify/pull/14449

refactor: use override rather than write a new function

---

models/vertex_ai/manifest.yaml
models/vertex_ai/models/llm/gemini-1.0-pro.yaml
models/vertex_ai/models/llm/gemini-1.5-flash-001.yaml
models/vertex_ai/models/llm/gemini-1.5-flash-002.yaml
models/vertex_ai/models/llm/gemini-1.5-pro-001.yaml
models/vertex_ai/models/llm/gemini-1.5-pro-002.yaml
models/vertex_ai/models/llm/llm.py
models/vertex_ai/requirements.txt

Same change with https://github.com/langgenius/dify/pull/13661 .
I also updated the version of the manifest and vertexai package.

Feat: support Vertex AI Grounding

---

models/openrouter/manifest.yaml
models/openrouter/models/llm/_position.yaml
models/openrouter/models/llm/o3-mini-2025-01-31.yaml
models/openrouter/models/llm/o3-mini.yaml

Sync the openrouter parts in https://github.com/langgenius/dify/pull/13129

feat(openrouter): update openrouter models and version to 0.0.4

---

tools/gitee_ai/manifest.yaml
tools/gitee_ai/provider/gitee_ai_tool.py
tools/gitee_ai/provider/gitee_ai_tool.yaml
tools/gitee_ai/tools/text-to-image.yaml

Gitee AI Tool 更新

---

models/cohere/manifest.yaml
models/cohere/models/text_embedding/text_embedding.py

Origin PR: https://github.com/langgenius/dify/pull/11864

chore: sync the change on main branch cohere

---

models/upstage/manifest.yaml
models/upstage/models/text_embedding/text_embedding.py

Origin PR: https://github.com/langgenius/dify/pull/11864

chore: sync the change on main branch upstage

---

tools/yahoo/manifest.yaml
tools/yahoo/requirements.txt

Fix https://github.com/langgenius/dify/issues/13403
0.2.51
0.2.54

Fix yahoo finance rate limit error due to outdated sdk ver

---

models/gemini/manifest.yaml
models/gemini/models/llm/gemini-2.0-flash-thinking-exp-0121.yaml

This PR sets the limits for the Gemini Flash Thinking Model to match the [documentation](https://cloud.google.com/vertex-ai/generative-ai/docs/thinking#limitations)

feat: Increase context and output size for flash thinking

---

models/anthropic/manifest.yaml
models/vertex_ai/manifest.yaml
models/vertex_ai/models/llm/llm.py
models/vertex_ai/requirements.txt

- Add support for JSON schema conversion for Vertex AI models
- Implement dynamic response MIME type and schema handling
- Downgrade vertexai package from 1.74.0 to 1.71.1
- Add recursive schema conversion method to support complex JSON schemas
- Fix https://github.com/langgenius/dify-official-plugins/issues/341

feat(vertex_ai): Enhance schema and response handling for Vertex AI LLM

---

models/openai/manifest.yaml
models/openai/models/llm/llm.py

https://github.com/langgenius/dify/pull/12222

fix(openai): update version to 0.0.10 and handle special case for 'yi' model in finish reason

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/llm/llm.py

feat(ark): show reasoning content for deepseek-r1

---

models/anthropic/manifest.yaml
models/anthropic/models/llm/claude-3-7-sonnet-20250219.yaml
models/anthropic/models/llm/llm.py
models/anthropic/requirements.txt

Fix https://github.com/langgenius/dify-official-plugins/issues/318
- Upgrade Anthropic library to version 0.48.0
- Enhance Claude 3.7 Sonnet model configuration
* Add new "thinking" mode parameter
* Introduce "thinking_budget" parameter
* Add "extended_output" beta feature support
* Increase max tokens to 128,000
- Improve token counting and streaming response handling
- Bump plugin version to 0.0.8

feat(anthropic): Update Claude 3 model configuration and Anthropic SDK

---

models/anthropic/manifest.yaml
models/anthropic/models/llm/llm.py

Correct the initialization parameters

fix(anthropic): Update AnthropicLargeLanguageModel initialization

---

models/gemini/manifest.yaml

chore(gemini): bump up

---

tools/duckduckgo/tools/ddgo_search.py

fix https://github.com/langgenius/dify/issues/14607

fix duckduckgo summary not work

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/llm.py

- Modify `incremental_output` parameter to match stream mode
- Add `is_reasoning` flag to track reasoning state during response generation
- Refactor response handling to improve stream processing logic

fix(tongyi): Update stream response handling in Tongyi LLM model

---

models/bedrock/manifest.yaml
models/bedrock/models/llm/us.meta.llama3-1-70b-instruct-v1.0.yaml

Feature:  llama 3.1 support

---

models/azure_openai/manifest.yaml
models/azure_openai/provider/azure_openai.yaml

1. Add new Azure API Version “2025-01-01-preview”
2. Update version to 0.0.6

Feat(Azure):Add new azure API Version

---

models/groq/manifest.yaml
models/groq/models/llm/_position.yaml
models/groq/models/llm/deepseek-r1-distill-llama-70b-specdec.yaml
models/groq/models/llm/deepseek-r1-distill-llama-70b.yaml
models/groq/models/llm/deepseek-r1-distill-qwen-32b.yaml
models/groq/models/llm/qwen-2.5-32b.yaml
models/groq/models/llm/qwen-2.5-coder-32b.yaml
models/groq/models/llm/qwen-qwq-32b.yaml
models/groq/provider/groq.yaml

1. add llms:
```yaml
- deepseek-r1-distill-qwen-32b
- qwen-2.5-32b
- qwen-2.5-coder-32b
- qwen-qwq-32b
```
2. fix `help.url`
https://groq.com/pricing/
https://console.groq.com/keys
https://console.groq.com/playground
By the way, I noticed that the pricing for other model configurations on Groq might have an error.

feat(groq): new LLMs

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/qwen2.5-vl-3b-instruct.yaml
models/tongyi/models/llm/qwen2.5-vl-7b-instruct.yaml

Sorry for making this mistake 😭

Fixed model names and labels in Qwen 2.5 VL model config file

---

tools/email/manifest.yaml
tools/email/provider/email.py
tools/email/tools/send_mail.py

Fix https://github.com/langgenius/dify/issues/15040

fix: email plugin validation error

---

tools/slidespeak/manifest.yaml
tools/slidespeak/tools/slides_generator.py

Fix https://github.com/langgenius/dify/issues/13754

fix: slidespeak cannot use

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/llm.py
models/tongyi/models/llm/qwen-long.yaml
models/tongyi/requirements.txt

Close https://github.com/langgenius/dify/issues/14951
Fix https://github.com/langgenius/dify/issues/15546
add file upload for tongyi for qwen-long
ref1: https://bailian.console.aliyun.com/#/model-market/detail/qwen-long
ref2: https://help.aliyun.com/zh/model-studio/developer-reference/openai-file-interface

feat(tongyi): add file-id support for qwen-long document feature

---

tools/tavily/manifest.yaml
tools/tavily/tools/tavily_extract.py
tools/tavily/tools/tavily_search.py

Tavily search and extract: map image URLS from the search and extract to the files[array] variable. (so it can be used in downstream nodes - like the LLM for vision).

Tavily search and extract images to files[array]

---

models/tongyi/manifest.yaml
models/tongyi/models/text_embedding/text_embedding.py

Addresses https://github.com/langgenius/dify-official-plugins/issues/432

add retry for 429 rate limit

---

models/gpustack/manifest.yaml
models/gpustack/models/llm/llm.py
models/gpustack/models/rerank/rerank.py
models/gpustack/models/speech2text/speech2text.py
models/gpustack/models/tts/tts.py
models/gpustack/provider/gpustack.yaml

fix https://github.com/langgenius/dify/issues/15539
fix https://github.com/gpustack/gpustack/issues/1453
This pr is going to
1. fix gpustack tts and speech2text not work in dify 1.0.
2. fix add GPUStack vllm rerank model 400 error.

fix model gpustack provider tts and speech2text not work

---

models/cohere/manifest.yaml
models/cohere/models/llm/c4ai-aya-expanse-32b.yaml
models/cohere/models/llm/c4ai-aya-expanse-8b.yaml
models/cohere/models/llm/command-a-03-2025.yaml
models/cohere/models/llm/command-nightly-chat.yaml
models/cohere/models/llm/command-r-03-2024.yaml
models/cohere/models/llm/command-r-08-2024.yaml
models/cohere/models/llm/command-r-plus-04-2024.yaml
models/cohere/models/llm/command-r-plus-08-2024.yaml
models/cohere/models/llm/command-r.yaml
models/cohere/models/llm/command-r7b-12-2024.yaml
models/cohere/models/llm/command-r7b-arabic-02-2025.yaml

feat: Command A, Command R and R Plus, Aya, r7b
fix: temperature

feat: update Cohere models

---

tools/email/manifest.yaml
tools/email/tools/send_mail.py

fix: email plugin have dup message

---

models/hunyuan/manifest.yaml
models/hunyuan/models/text_embedding/hunyuan-text-embedding.yaml
models/hunyuan/models/text_embedding/text_embedding.py
models/hunyuan/requirements.txt

Update to use the latest method to use hunyuan embedding, see https://cloud.tencent.com/document/api/1772/115343.

upgrade tencentcloud sdk to use lkeap module for embedding

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/llm/llm.py
models/volcengine_maas/models/llm/models.py
models/volcengine_maas/requirements.txt

feat:support tool calling for deepseek V3&R1
feat:change the thinking tag style
chore:bump plugin sdk version to b74

feat:support tool calling for deepseek V3&R1,and change the thinking tag style

---

tools/email/manifest.yaml
tools/email/requirements.txt
tools/email/tools/send.py
tools/email/tools/send_mail.py
tools/email/tools/send_mail.yaml
tools/email/tools/send_mail_batch.py
tools/email/tools/send_mail_batch.yaml

what change:
1. [fix: update dify_plugin version to 0.0.1b74](https://github.com/langgenius/dify-official-plugins/commit/d464b2b4585fcefbeb4c0e84f5a78826af12273d)
2. [fix: change return type to generator for email sending tool](https://github.com/langgenius/dify-official-plugins/commit/f44df9eb6f1e2113db22a74a85424d146f769a56)
3. [feat: enhance email sending tool to support CC and BCC recipients](https://github.com/langgenius/dify-official-plugins/commit/880029a92af76d603065e53462aeb792ff7648a1)
4. [fix: update plugin version to 0.0.5](https://github.com/langgenius/dify-official-plugins/commit/a3c5890acc71602ee733d6d4afa26e9ef65e040c)

feat: enhance email sending tool to support CC and BCC recipients

---

tools/telegraph/manifest.yaml
tools/telegraph/provider/telegraph.yaml
tools/telegraph/requirements.txt

fix: space missing when format

---

tools/azuredalle/manifest.yaml
tools/azuredalle/requirements.txt
tools/azuredalle/tools/dalle3.py

- bump version `0.0.3`
- `from base64 import b64decode` => `import base64` 
- bump sdk version to `dify_plugin==0.0.1b74`
Fix https://github.com/langgenius/dify/issues/16797

fix: azuredalle not working 

---

tools/searxng/README.md

The previous README is no longer up to date.

update the searxng readme

---

.github/pull_request_template.md

Related issue:
- https://github.com/langgenius/dify/issues/16393

docs: Require test results for pull request

---

tools/perplexity/manifest.yaml
tools/perplexity/tools/perplexity_search.py

fix https://github.com/langgenius/dify/issues/17080
maybe fix: https://github.com/langgenius/dify-official-plugins/issues/600
> [!IMPORTANT]
> Visual proof is required for Bug fixes, New features, Breaking changes:
- Screenshots or Video/GIF (if applicable):
> [!NOTE]
> For Non-LLM Plugin Changes:
> - **Bug fixes**:
>   - [ ] Show the fix working
> - **New features**:
>   - [ ] Demonstrate the functionality
> - **Breaking changes**:
>   - [ ] Show both old and new behavior
>
> For LLM Plugin Changes:
> - **Bug fixes**:
>   - [x] Show the fix working with example inputs/outputs
> - **New features**:
>   - [ ] Demonstrate the functionality with example inputs/outputs
> - **Breaking changes** (requires comprehensive testing):
>     - Conversation …

fix perplexity search_domain_filter parameter

---

.github/pull_request_template.md

docs: update pull request template to improve clarity and consistency in testing guidelines

---

tools/wolframalpha/manifest.yaml
tools/wolframalpha/tools/wolframalpha.py

> [!IMPORTANT]
> [!NOTE]
>   - [x] Show the Fix working
> …

fix: type error in wolframalpha

---

tools/github/manifest.yaml
tools/github/provider/github.py
tools/github/provider/github.yaml
tools/github/tools/github_repositories.py
tools/github/tools/github_repositories.yaml
tools/github/tools/github_repository_readme.py

fix: standardize 'GitHub' spelling across files

---

models/azure_openai/manifest.yaml
models/azure_openai/models/constants.py
models/azure_openai/models/llm/llm.py
models/azure_openai/provider/azure_openai.yaml

This PR adds:
- ✅ support for **gpt-4.5-preview** for Azure OpenAI model provider plugin.
- ✅ support for the latest API version **2025-03-01-preview**
As a minor fix, this PR also corrects price table for gpt-4o-* models.
> [!IMPORTANT]
> [!NOTE]
>
>   - [x] Demonstrate the Functionality with Example Inputs/Outputs
>   - …

feat(azure_openai): support gpt-4.5-preview

---

models/openai/manifest.yaml
models/openai/models/llm/o1-mini.yaml
models/openai/models/llm/o3-mini-2025-01-31.yaml

Correction of o-series models' support for json_schema
reference: https://platform.openai.com/docs/guides/structured-outputs?api-mode=chat
> [!IMPORTANT]
> [!NOTE]
>
> [LLM Models Test Example](https://github.com/langgenius/dify-official-plugins/blob/main/.assets/test-examples/llm-plugin-tests/llm_test_example.md)
> …

chore(openai): correction of o-series models' support for json_schema

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/requirements.txt

SDK fix: https://github.com/langgenius/dify-plugin-sdks/pull/73
Fix https://github.com/langgenius/dify-official-plugins/issues/638
Fix https://github.com/langgenius/dify-official-plugins/issues/575
Fix https://github.com/langgenius/dify/issues/17335
Fix https://github.com/langgenius/dify/issues/17305
> [!IMPORTANT]
> [!NOTE]
>
>   - [ ] Demonstrate the Functionality with Example …

fix: validation error for volcengine_maas

---

agent-strategies/cot_agent/manifest.yaml
agent-strategies/cot_agent/strategies/function_calling.py

when max_iteration=1 need to make tool call and return response
fix https://github.com/langgenius/dify-official-plugins/issues/587
after fixing it on local plugin installation，I can use agent function call when set max_iteration=1

fix:587 when max_iteration=1 need to make tool call and return response

---

models/xinference/manifest.yaml
models/xinference/models/llm/llm.py

fix agent function call error when use xinference as model provider:
https://github.com/langgenius/dify/issues/14904#issuecomment-2724775300
**before this fix:** 
**after fixing it on local plugin installation，I can use agent function call when use xinference as model provider**

fix xinference error when agent function call

---

models/gemini/manifest.yaml
models/gemini/models/llm/llm.py

1. fix token count not response ,   https://github.com/langgenius/dify-official-plugins/issues/655
2. improve grounding feature
3. improve cache,  now cache the file url and mime type instead of the file name,  and then can directly transfer it to LLM
4. `json_schema` and `grounding` can't use at same time
> [!IMPORTANT]
1. token count
2. grounding
before:
after:
> [!NOTE]
>
>   - [ …

improve gemini models

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/qwen2.5-0.5b-instruct.yaml
models/tongyi/models/llm/qwen2.5-1.5b-instruct.yaml
models/tongyi/models/llm/qwen2.5-14b-instruct-1m.yaml
models/tongyi/models/llm/qwen2.5-14b-instruct.yaml
models/tongyi/models/llm/qwen2.5-32b-instruct.yaml
models/tongyi/models/llm/qwen2.5-3b-instruct.yaml
models/tongyi/models/llm/qwen2.5-72b-instruct.yaml
models/tongyi/models/llm/qwen2.5-7b-instruct-1m.yaml
models/tongyi/models/llm/qwen2.5-7b-instruct.yaml

closes https://github.com/langgenius/dify-official-plugins/issues/636
https://help.aliyun.com/zh/model-studio/qwen-function-calling?spm=a2c4g.11186623.help-menu-2400256.d_0_1_4.1bd5429eo4Nkuh
> [!IMPORTANT]
> [!NOTE]
>
> …

chore:update qwen2.5 series parameters

---

models/openrouter/manifest.yaml
models/openrouter/requirements.txt

upgrading openrouter to dify_plugin~=0.0.1b76 fix cpu usage 100%

---

models/novita/manifest.yaml
models/novita/requirements.txt

upgrading novita to dify_plugin~=0.0.1b76 fix cpu usage 100%

---

models/ollama/manifest.yaml
models/ollama/models/llm/llm.py

Add response_format field to ollama to support structured output
> [!IMPORTANT]
> [!NOTE]
>
> [LLM Models Test Example](https://github.com/langgenius/dify-official-plugins/blob/main/.assets/test-examples/llm-plugin-tests/llm_test_example.md)
>   - [x] Demonstrate the Functionality with Example Inputs/Outputs
>   - …

feat: add structrued output to ollama

---

models/huggingface_tei/models/text_embedding/text_embedding.py

Optimize the text embedding model by replacing the server's /tokenize interface (which frequently throws errors on Huawei and NVIDIA GPUs) with the GPT2 tokenizer. Simplify the token counting logic and adjust the text truncation method to improve performance.
Alternatively, if you'd like a more concise version:
Optimized the text embedding model by switching to the GPT2 tokenizer (replacing the error-prone /tokenize interface on Huawei/NVIDIA GPUs), simplifying token counting, and adjusting text truncation for better performance.
Fix https://github.com/langgenius/dify/issues/15035
> [!IMPORTANT]
> [!NOTE]
>   - …

fix: Optimize the text embedding model by replacing the server's /tokenize interface

---

tools/dropbox/.env.example
tools/dropbox/GUIDE.md
tools/dropbox/LICENSE.md
tools/dropbox/PRIVACY.md
tools/dropbox/README.md
tools/dropbox/_assets/icon.svg
tools/dropbox/dropbox_utils.py
tools/dropbox/main.py
tools/dropbox/manifest.yaml
tools/dropbox/provider/dropbox.py
tools/dropbox/provider/dropbox.yaml
tools/dropbox/requirements.txt
tools/dropbox/tools/create_folder.py
tools/dropbox/tools/create_folder.yaml
tools/dropbox/tools/delete_file.py
tools/dropbox/tools/delete_file.yaml
tools/dropbox/tools/download_file.py
tools/dropbox/tools/download_file.yaml
tools/dropbox/tools/dropbox.py
tools/dropbox/tools/dropbox.yaml
tools/dropbox/tools/list_files.py
tools/dropbox/tools/list_files.yaml
tools/dropbox/tools/search_files.py
tools/dropbox/tools/search_files.yaml
tools/dropbox/tools/upload_file.py
tools/dropbox/tools/upload_file.yaml

feat: dropbox

---

tools/searxng/manifest.yaml
tools/searxng/tools/searxng_search.py
tools/searxng/tools/searxng_search.yaml

Update the SearXNG plugin version to 0.0.3 and add a time range parameter to support time filtering for the search functionality.
> [!IMPORTANT]
> Visual proof is required for Bug fixes, New features, Breaking changes:
- Screenshots or Video/GIF (if applicable):
> [!NOTE]
> For Non-LLM Plugin Changes:
> - **Bug fixes**:
>   - [ ] Show the fix working
> - **New features**:
>   - [ ] Demonstrate the functionality
> - **Breaking changes**:
>   - [ ] Show both old and new behavior
>
> For LLM Plugin Changes:
> - **Bug fixes**:
>   - [ ] Show the fix working with example inputs/outputs
> - **New features**:
>   - [x] Demonstrate the functionality with example inputs/outputs
> - **Breaking changes** (requires comprehensive testing):
>     - Conversation …

feat: add time_range parameter

---

models/x/manifest.yaml
models/x/models/llm/grok-3-beta.yaml
models/x/models/llm/grok-3-fast-beta.yaml
models/x/models/llm/grok-3-mini-beta.yaml
models/x/models/llm/grok-3-mini-fast-beta.yaml
models/x/requirements.txt

xAI Official Docs: https://docs.x.ai/docs/models#models-and-pricing
Close https://github.com/langgenius/dify-official-plugins/issues/689
Close https://github.com/langgenius/dify-official-plugins/issues/598
Close https://github.com/langgenius/dify-official-plugins/issues/400
> [!IMPORTANT]
> [!NOTE]
>
>   - [x] Demonstrate the Functionality with Example Inputs/Outputs
> - **Breaking …

feat: add grok-3 model variants

---

.github/pull_request_template.md

- Added a note directing community contributions to a separate repository.
- Streamlined checklists for non-plugin and plugin changes.
- Clarified checklists for LLM-related functionalities (e.g., message flow, multimodal input/output, structured formats).
- Emphasized version bumping in Manifest.yaml with detailed guidelines for versioning.
- Simplified testing instructions for local and SaaS environments with clearer requirements.

docs: Update pull_request_template.md

---

models/gpustack/manifest.yaml
models/gpustack/provider/gpustack.yaml

Due to openai_compatible custom models having default support for stream_tool_call, Agent applications using these models will automatically select Function Call mode, resulting in execution. Adding the stream tool call params to control the agent mode.
Fixes https://github.com/langgenius/dify/issues/17917
> [!IMPORTANT]
> [!NOTE]
>
>   - [ ] Demonstrate the Functionality with …

fix(gpustack): error in mode selection for the agent app

---

models/openai/manifest.yaml
models/openai/models/llm/_position.yaml
models/openai/models/llm/gpt-4.1-2025-04-14.yaml
models/openai/models/llm/gpt-4.1-mini-2025-04-14.yaml
models/openai/models/llm/gpt-4.1-mini.yaml
models/openai/models/llm/gpt-4.1-nano-2025-04-14.yaml
models/openai/models/llm/gpt-4.1-nano.yaml
models/openai/models/llm/gpt-4.1.yaml

- https://openai.com/index/gpt-4-1/
- Updated version in manifest.yaml to 0.0.17.
- Added new model variants in _position.yaml for gpt-4.1 series.

feat: add gpt4.1 family to openai

---

models/openai/manifest.yaml
models/openai/models/tts/gpt-4o-mini-tts.yaml
models/openai/models/tts/tts-1-hd.yaml
models/openai/provider/openai.py
models/openai/requirements.txt

https://platform.openai.com/docs/api-reference/audio/createSpeech
- Add some new voices.
- Add new tts model gpt-4o-mini-tts which is faster and cheaper,and has higher performance.
- Change default LLM model for validate credentials  from gpt-3.5-turbo to gpt-4o-mini(cheaper and newer).
-

feat:add gpt-4o-mini-tts for openai

---

models/bedrock/manifest.yaml
models/bedrock/models/llm/llm.py
models/bedrock/provider/amazon-bedrock.yaml
models/bedrock/provider/get_bedrock_client.py

> [!IMPORTANT]
> [!NOTE]
>   - [x] Demonstrate the Functionality
>
>   - [x] Demonstrate the Functionality with Example Inputs/Outputs …

feat: bedrock llm support proxy url

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/_position.yaml
models/tongyi/models/llm/qwen-max-0125.yaml
models/tongyi/models/llm/qwen-max.yaml
models/tongyi/models/llm/qwen-plus-0112.yaml
models/tongyi/models/llm/qwen-plus-0125.yaml
models/tongyi/models/llm/qwen-plus-0206.yaml
models/tongyi/models/llm/qwen-plus-0624.yaml
models/tongyi/models/llm/qwen-plus-0723.yaml
models/tongyi/models/llm/qwen-plus-0806.yaml
models/tongyi/models/llm/qwen-plus-0919.yaml
models/tongyi/models/llm/qwen-plus-1125.yaml
models/tongyi/models/llm/qwen-plus-1127.yaml
models/tongyi/models/llm/qwen-plus-1220.yaml
models/tongyi/models/llm/qwen-plus-latest.yaml
models/tongyi/models/llm/qwen-plus.yaml

- Added new models: qwen-max-0125, qwen-plus-0112, qwen-plus-0125, qwen-plus-1125, qwen-plus-1127, and qwen-plus-1220 with detailed parameter rules and pricing.
- Updated qwen-max-latest and qwen-max to have increased context size and adjusted pricing.
- Modified qwen-plus models to change mode from 'completion' to 'chat' and added multi-tool-call and stream-tool-call features.
- Standardized max_tokens default value to 8192 across relevant models.

feat & fix: Add new models and update existing configurations for qwen series

---

tools/fal/.env.example
tools/fal/manifest.yaml
tools/fal/provider/fal.yaml
tools/fal/requirements.txt
tools/fal/tools/clarity_upscaler.py
tools/fal/tools/clarity_upscaler.yaml

* Bump version in manifest.yaml to 0.0.3.
* Update requirements.txt to require a compatible version of dify_plugin.
* Add clarity_upscaler.yaml to the tools list in fal.yaml.

feat: Add clarity_upscaler to fal

---

models/openai/manifest.yaml
models/openai/models/llm/llm.py

fixed: https://github.com/langgenius/dify-official-plugins/issues/721
before:
after:

fix: openai model changed when encoding_for_model KeyError

---

models/azure_openai/manifest.yaml
models/azure_openai/models/constants.py
models/azure_openai/models/llm/llm.py
models/azure_openai/provider/azure_openai.yaml
models/azure_openai/requirements.txt

feat: add azure gpt-4.1

---

tools/comfyui/manifest.yaml
tools/comfyui/tools/comfyui_stable_diffusion.yaml

feat: More dynamic parameters for ComfyUI Txt2Img

---

.github/pull_request_template.md

Update pull request template to include Dify Plugin SDK version

docs: Update pull request template to include Dify Plugin SDK version

---

tools/searxng/manifest.yaml
tools/searxng/tools/searxng_search.yaml

fix: searxng does not support time_range=week

---

tools/yahoo/.env.example
tools/yahoo/manifest.yaml
tools/yahoo/requirements.txt
tools/yahoo/tools/analytics.py
tools/yahoo/tools/news.py

Fixes https://github.com/langgenius/dify-official-plugins/issues/729
* Updated requirements.txt to specify compatible versions for dify_plugin and yfinance.
* Refactored YahooFinanceAnalyticsTool to improve data processing and error handling.
* Renamed YahooFinanceSearchTickerTool to YahooFinanceNewsTool and enhanced news extraction logic for better clarity and structure.
before
after

fix: update requirements and refactor YahooFinanceAnalyticsTool and YahooFinanceNewsTool

---

models/gemini/manifest.yaml
models/gemini/models/llm/gemini-2.5-flash-preview-04-17.yaml
models/gemini/requirements.txt

add gemini 2.5 flash preview to google ai studio
Note: The thinking feature is currently unavailable due to a version conflict between the lastest gen-ai httpx dependencies (version 0.28.1) and the Dify plugin SDK (version 0.27.0).

chore: add gemini 2.5 flash preview to google ai studio

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/llm/models.py
models/volcengine_maas/provider/volcengine_maas.yaml
models/volcengine_maas/requirements.txt

add new model `Doubao-1.5-thinking-pro`

Feat: add doubao 1.5 thinking pro

---

models/huggingface_tei/models/text_embedding/text_embedding.py

fix: Repair the method of obtaining TGI api_key

---

models/volcengine_maas/models/llm/models.py
models/volcengine_maas/provider/volcengine_maas.yaml

https://www.volcengine.com/docs/82379/1330310#doubao-1-5-vision

feat: add volcengine 3 models

---

models/openai/manifest.yaml
models/openai/models/llm/o3-2025-04-16.yaml
models/openai/models/llm/o3.yaml
models/openai/models/llm/o4-mini-2025-04-16.yaml
models/openai/models/llm/o4-mini.yaml

add o4-mini to OpenAi model Provider

---

tools/email/manifest.yaml
tools/email/provider/email.yaml
tools/email/tools/send.py
tools/email/tools/send_mail.py
tools/email/tools/send_mail.yaml
tools/email/tools/send_mail_batch.yaml

- Attempting to send emails through AWS's Simple Email Service (SES) was leading to problems.
- `email_account` for SES is a non-email SMTP credential set up through AWS.
- Trying to use just a from address and the SMTP credential password was not passing SES login validation
- Trying to use the non-email credential in `email_account`, the tool was also using the non-email credential as the sender address and it was failing regex validation on tool side. 
This pull request adds the option to define `email_account` and `sender_address` as two separate values so that SES can be used for email sending. 
Fix also adds the ability to define a `reply_to` address so that email replies can go somewhere other than the sender's inbox.

feat: enhancement to email tool plugin for SES email with reply-to

---

tools/openai/manifest.yaml

- https://github.com/langgenius/dify-official-plugins/pull/794#issuecomment-2830392296
Im making this changes based on how Siliconflow model and Siliconflow tool's naming works
https://github.com/langgenius/dify-official-plugins/blob/main/models/siliconflow/manifest.yaml
https://marketplace.dify.ai/plugins/langgenius/siliconflow
https://github.com/langgenius/dify-official-plugins/blob/main/tools/siliconflow/manifest.yaml
https://marketplace.dify.ai/plugins/langgenius/siliconflow_tool

fix: resolve openai model and openai tool conflict

---

models/gemini/README.md
models/gemini/manifest.yaml
models/gemini/models/llm/llm.py

Reverts langgenius/dify-official-plugins#687. 
This PR should only be merged after the associated changes https://github.com/langgenius/dify/pull/17372 in the Dify are merged.

Revert "feat(gemini): Update Gemini Models to support image multimodal output"

---

models/siliconflow/manifest.yaml
models/siliconflow/models/llm/deepseek-r1-distill-llama-70B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-llama-8B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-1.5B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-14B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-32B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-7B.yaml
models/siliconflow/models/llm/deepseek-v2.5.yaml
models/siliconflow/models/llm/deepseek-v3-pro.yaml
models/siliconflow/models/llm/deepseek-v3.yaml
models/siliconflow/models/llm/internvl2-llama3-76b.yaml
models/siliconflow/models/llm/janus-pro-7B.yaml
models/siliconflow/models/llm/meta-mlama-3.1-70b-instruct.yaml

dify cloud with local enviroment

update siliconflow configs

---

.github/workflows/pre-check-plugin.yaml

ci: version overwrite is no longer allowed

---

tools/mineru/README.md

This PR updates the documentation for the MinerU plugin to improve clarity, formatting, and provide better guidance in the FAQs section based on recent user feedback and common issues (like the `FILES_URL` configuration).
*(Documentation changes only)*
*(Documentation changes only)*
*(Documentation changes only)*
*(Documentation changes only)*
*(Documentation changes only)*
---

doc: Update README.md for MinerU plugin

---

.github/pull_request_template.md

dify plugin ver instruction follow up

docs: dify plugin ver instruction follow up

---

models/ollama/manifest.yaml
models/ollama/requirements.txt

bump sdk version

---

models/openai/manifest.yaml
models/openai/models/llm/o4-mini-2025-04-16.yaml
models/openai/requirements.txt

- Bump version from 0.0.20 to 0.0.21 in manifest.yaml
- Update dify_plugin dependency version in requirements.txt from >=0.1.0,<0.2.0 to >=0.2.0,<0.3.0
- Modify model labels in o4-mini-2025-04-16.yaml to include the full date
before
after

chore: correct chatgpt o4 mini endpoint

---

models/minimax/manifest.yaml
models/minimax/provider/minimax.yaml

fix: https://github.com/langgenius/dify-official-plugins/issues/821
fix: https://github.com/langgenius/dify-official-plugins/pull/815

fix: minimax yaml config

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/llm.py
models/tongyi/models/llm/qwen-plus-2025-04-28.yaml
models/tongyi/models/llm/qwen-plus-latest.yaml
models/tongyi/models/llm/qwen-turbo-2025-04-28.yaml
models/tongyi/models/llm/qwen-turbo-latest.yaml
models/tongyi/models/llm/qwen3-0.6b.yaml
models/tongyi/models/llm/qwen3-14b.yaml
models/tongyi/models/llm/qwen3-235b-a22b.yaml
models/tongyi/models/llm/qwen3-30b-a3b.yaml
models/tongyi/models/llm/qwen3-32b.yaml
models/tongyi/models/llm/qwen3-4b.yaml
models/tongyi/models/llm/qwen3-8b.yaml

fix the opensource version of Qwen3 model and add the commercial version of Qwen3 model

---

models/siliconflow/manifest.yaml
models/siliconflow/models/llm/llm.py
models/siliconflow/models/llm/qwen3-14b.yaml
models/siliconflow/models/llm/qwen3-235b-a22b.yaml
models/siliconflow/models/llm/qwen3-30b-a3b.yaml
models/siliconflow/models/llm/qwen3-32b.yaml
models/siliconflow/models/llm/qwen3-8b.yaml
models/siliconflow/provider/siliconflow.py
models/siliconflow/requirements.txt

feat: add qwen3 to siliconflow

---

models/gitee_ai/manifest.yaml
models/gitee_ai/models/llm/llm.py

fix #827
-  [x] Dify Version is: 1.2.0, I have Tested My Changes on Local Deployment Dify with a Clean Environment That Matches the Production Configuration.

remove reduntant and invalid method “validate_credentials ”

---

models/openai_api_compatible/manifest.yaml
models/openai_api_compatible/models/llm/llm.py

https://github.com/langgenius/dify-official-plugins/pull/830

fix: override get_customizable_model_schema

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/client.py
models/volcengine_maas/models/llm/llm.py
models/volcengine_maas/models/llm/models.py

feat: add content moderation bypass option for volcengine_maas

---

models/azure_openai/manifest.yaml
models/azure_openai/requirements.txt

Bump SDK version from 0.1.x to 0.2.x.

feat(azure_openai): bump sdk version to 0.2.x

---

models/bedrock/manifest.yaml
models/bedrock/models/llm/cache_config.py
models/bedrock/models/llm/llm.py
models/bedrock/requirements.txt

Only add prompt cache checkpoint for system message and second-to-last user message

feat: modify prompt cache

---

models/gemini/manifest.yaml
models/gemini/models/llm/_position.yaml
models/gemini/models/llm/gemini-2.5-pro-preview-05-06.yaml
models/gemini/requirements.txt

add(models/gemini): gemini-2.5-pro-preview-05-06

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/llm.py

fixed https://github.com/langgenius/dify/issues/19364
fix https://github.com/langgenius/dify-official-plugins/issues/861
fix https://github.com/langgenius/dify-official-plugins/issues/873
fix https://github.com/langgenius/dify-official-plugins/issues/834

fix: incremental_output logic for tool calling support

---

tools/comfyui/manifest.yaml
tools/comfyui/tools/comfyui_workflow.yaml

close https://github.com/langgenius/dify/issues/18822
0.0.7
1.3.1

improve: make comfyUI plugin all input can use variable

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/llm.py

fix (tongyi): Qwen3 open-source edition and QwQ models tool_calls error

---

tools/google/manifest.yaml
tools/google/provider/google.yaml
tools/google/tools/google-countries.json
tools/google/tools/google-languages.json
tools/google/tools/google_image_search.py
tools/google/tools/google_image_search.yaml

support google image search and enhance google search

feat:support google image search

---

models/gitee_ai/manifest.yaml
models/gitee_ai/models/llm/llm.py
models/gitee_ai/models/tts/tts.py
models/gitee_ai/provider/gitee_ai.yaml

update name, Support customizable model

Gitee AI:update name, Support customizable model

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/llm/models.py
models/volcengine_maas/provider/volcengine_maas.yaml

feat: add Doubao-1.5-thinking-vision-pro model

---

models/llama_api/manifest.yaml
models/llama_api/models/llm/llm.py
models/llama_api/provider/llama-api.py

Adding Copyright header on the files as per requirements from Meta Open Source team.

Llama API Plugin - Add headers

---

models/siliconflow/manifest.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-1.5B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-14B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-32B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-7B.yaml
models/siliconflow/models/llm/deepseek-r1-pro.yaml
models/siliconflow/models/llm/deepseek-r1.yaml
models/siliconflow/models/llm/deepseek-v3-pro.yaml
models/siliconflow/models/llm/deepseek-v3.yaml
models/siliconflow/models/llm/glm4-9b-chat.yaml
models/siliconflow/models/llm/qwen2.5-14b-instruct.yaml
models/siliconflow/models/llm/qwen2.5-32b-instruct.yaml
models/siliconflow/models/llm/qwen2.5-72b-instruct-128k.yaml
models/siliconflow/models/llm/qwen2.5-72b-instruct.yaml
models/siliconflow/models/llm/qwen2.5-7b-instruct.yaml

Fix the inability to select models supporting tool calls in siliconflow.
[Function Calling 支持模型列表](https://docs.siliconflow.com/en/userguide/guides/function-calling#3-supported-models)

chore: upd siliconflow parameters

---

tools/email/main.py
tools/email/manifest.yaml
tools/email/tools/send_mail.py

This PR addresses **Issue #927: Email File Attachment Error** by introducing a comprehensive and fault-tolerant mechanism for handling file attachments in the email plugin.
- **Enhanced File Type Support**  
Supports text, image, audio, and binary files using appropriate MIME types.
- **Error Prevention & Handling**  
- Validates file existence and size before attachment.  
- Isolates attachment errors using per-file try/catch blocks to prevent total failure.
- **Detailed Logging**  
- Warnings for skipped/invalid files.  
- Error logs for failed attachments to aid in debugging.
- **Robust Exception Management**  
Gracefully handles both API-specific and general exceptions with clear error messaging.
This update ensures more reliable email delivery even in the presence of problematic …

Solution for Issue #927: Email File Attachment Error #ieeesoc

---

tools/confluence/manifest.yaml
tools/confluence/provider/confluence.yaml
tools/confluence/tools/auth.py

close https://github.com/langgenius/dify-official-plugins/issues/911

feat: allow to use both bearer and basic token

---

models/siliconflow/manifest.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-1.5B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-14B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-32B.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-7B.yaml
models/siliconflow/models/llm/deepseek-r1-pro.yaml
models/siliconflow/models/llm/deepseek-r1.yaml
models/siliconflow/models/llm/deepseek-v3-pro.yaml
models/siliconflow/models/llm/deepseek-v3.yaml
models/siliconflow/models/llm/glm4-9b-chat.yaml
models/siliconflow/models/llm/qwen2.5-14b-instruct.yaml
models/siliconflow/models/llm/qwen2.5-32b-instruct.yaml
models/siliconflow/models/llm/qwen2.5-72b-instruct-128k.yaml
models/siliconflow/models/llm/qwen2.5-72b-instruct.yaml
models/siliconflow/models/llm/qwen2.5-7b-instruct.yaml

revert(siliconflow): tool-call features

---

models/bedrock/manifest.yaml
models/bedrock/models/llm/llm.py
models/bedrock/provider/bedrock.yaml
models/bedrock/provider/get_bedrock_client.py

feat: support bedrock_endpoint_url for bedrock-runtime

---

models/anthropic/manifest.yaml
models/anthropic/models/llm/_position.yaml
models/anthropic/models/llm/claude-opus-4-20250514.yaml
models/anthropic/models/llm/claude-sonnet-4-20250514.yaml
models/anthropic/requirements.txt

https://docs.anthropic.com/en/docs/about-claude/models/migrating-to-claude-4

chore: add claude 4 series

---

models/vertex_ai/manifest.yaml
models/vertex_ai/models/llm/llm.py

fix(vertexai): Fix using tool in Vertex AI

---

models/openllm/manifest.yaml
models/openllm/requirements.txt

bump openllm dify-plugin version to >=0.2.0

---

models/openai/manifest.yaml
models/openai/models/llm/llm.py

Add o4 model support for token counting

feat(openai): Add o4 model support for token counting

---

tools/searxng/README.md

This PR addresses the need for improved documentation to help users successfully set up and use the SearXNG plugin. The current README lacks comprehensive setup instructions, troubleshooting guidance, and detailed parameter explanations, leading to user confusion and setup difficulties.
**Context for this change:**
- Users frequently encounter Docker configuration issues
- Lack of clear SearXNG settings.yml modification instructions
- Missing troubleshooting section for common problems
- No detailed parameter documentation or usage examples
- Insufficient guidance for different deployment scenarios
**Testing performed:**
- ✅ Verified all markdown formatting renders correctly
- ✅ Tested all Docker commands and configuration examples
- ✅ Validated all curl commands and API endpoints
- ✅ …

searxng readme improvement #IEEESOC

---

models/x/manifest.yaml
models/x/models/llm/grok-2-1212.yaml
models/x/models/llm/grok-2-vision-1212.yaml
models/x/models/llm/grok-3-beta.yaml
models/x/models/llm/grok-3-fast-beta.yaml
models/x/models/llm/grok-3-mini-beta.yaml
models/x/models/llm/grok-3-mini-fast-beta.yaml
models/x/models/llm/grok-beta.yaml
models/x/models/llm/grok-vision-beta.yaml
models/x/requirements.txt

feat(model/xai): optimize model config with reusable templates and enable Structured Outputs for Grok model

feat(model/xai): optimize model config with reusable templates and enable Structured Outputs for Grok model

---

tools/arxiv/README.md
tools/searxng/README.md

This PR addresses the need for improved documentation to help users successfully set up and use the ArXiv plugin. The current README lacks comprehensive setup instructions, usage examples, and detailed parameter explanations, leading to user confusion and implementation difficulties.
Context for this change:
- Users frequently encounter issues understanding ArXiv search query formats
- Lack of clear examples for different search types (keywords, authors, ArXiv IDs)
- Missing API reference and troubleshooting guidance
- No detailed usage examples for different Dify application types
Testing performed:
✅ Verified all markdown formatting renders correctly
✅ Tested all ArXiv search examples and query formats
✅ Validated all code snippets and external links
✅ Confirmed documentation flow from …

ArXiv plugin Readme improvement #ieeesoc

---

models/siliconflow/manifest.yaml
models/siliconflow/models/llm/llm.py
models/siliconflow/models/llm/qwen3-14b.yaml
models/siliconflow/models/llm/qwen3-235b-a22b.yaml
models/siliconflow/models/llm/qwen3-30b-a3b.yaml
models/siliconflow/models/llm/qwen3-32b.yaml
models/siliconflow/models/llm/qwen3-8b.yaml

固化 ```credentials["function_calling_type"] = "tool_call"```
由于 
```deepseek-ai/DeepSeek-V3``` -> 多用几轮 tools 容易异常
```Qwen/Qwen2.5-72B-Instruct``` -> Ai吐出内容不会换行
所以这些没有被加上 stream-tool-call

feat(siliconflow): qwen3 support tool_call

---

models/bedrock/manifest.yaml
models/bedrock/models/llm/anthropic-claude.yaml
models/bedrock/models/llm/llm.py
models/bedrock/models/llm/model_ids.py

Add support for claude 4 sonnet / claude 4 opus

---

.github/workflows/pre-check-plugin.yaml
.github/workflows/upload-merged-plugin.yaml
models/openai/main.py
models/openai/manifest.yaml
tests/models/__mockserver/openai.py
tests/models/openai/test_openai.py

- Refactor pre-check-plugin.yaml to use 'uv' for Python setup and dependency management.
- Modify paths to ignore tests in both pre-check and upload-merged workflows.
- Enhance plugin validation and testing steps to utilize 'uv' for running Python scripts.
- Clean up main.py by removing unnecessary sys.path modifications.
- Add new test file for OpenAI model.

refactor: enforce enabling integration tests on GitHub workflows

---

models/gemini/manifest.yaml
models/gemini/models/llm/llm.py

Signed-off-by: -LAN- <laipz8200@outlook.com>
fixes #980

fix: enhance function call ID generation

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/llm/llm.py

fix(volcengine_maas): wrong completion_tokens of usage #998

---

tools/comfyui/manifest.yaml
tools/comfyui/provider/comfyui.py
tools/comfyui/provider/comfyui.yaml
tools/comfyui/tools/comfyui_client.py
tools/comfyui/tools/depth_anything.py
tools/comfyui/tools/depth_pro.py
tools/comfyui/tools/download_civitai.py
tools/comfyui/tools/download_huggingface.py
tools/comfyui/tools/face_swap.py
tools/comfyui/tools/img2vid.py
tools/comfyui/tools/list_models.py
tools/comfyui/tools/list_samplers.py
tools/comfyui/tools/txt2img.py
tools/comfyui/tools/txt2img.yaml
tools/comfyui/tools/upscale.py
tools/comfyui/tools/workflow.py

Add API Token for ComfyUI for secure access (based on ComfyUI-Sentinel plugin).
Need to install this plugin for comfyui.（https://github.com/LucipherDev/ComfyUI-Sentinel）

Add API Token for ComfyUI for secure access (based on ComfyUI-Sentinel plugin).

---

models/vertex_ai/manifest.yaml
models/vertex_ai/models/llm/llm.py

Related Issue: fix #945 
```python
[vertex_ai] Error: PluginInvokeError: {"args":{},"error_type":"TypeError","message":"'Tool' object is not iterable"}
```

fix(vertexai): Fix to iter tools

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/client.py
models/volcengine_maas/models/llm/models.py
models/volcengine_maas/requirements.txt

https://www.volcengine.com/docs/82379/1494384?redirect=1#%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0

feat: doubao vision support video

---

models/vertex_ai/manifest.yaml
models/vertex_ai/models/llm/gemini-1.5-flash-002.yaml
models/vertex_ai/models/llm/gemini-1.5-pro-002.yaml
models/vertex_ai/models/llm/gemini-2.0-flash-001.yaml
models/vertex_ai/models/llm/gemini-2.5-flash-preview-04-17.yaml
models/vertex_ai/models/llm/gemini-2.5-pro-preview-03-25.yaml
models/vertex_ai/models/llm/gemini-2.5-pro-preview-05-06.yaml
models/vertex_ai/models/llm/llm.py
models/vertex_ai/requirements.txt

This pull request enables the Grounding feature for Vertex AI Gemini models.
- This PR introduces Grounding functionality for Vertex AI Gemini.
| | | |
|--------|-------|-------|
| ![ダウンロード (5)](https://github.com/user-attachments/assets/e4e74815-59ff-45bd-b4cb-d3de464e316f) | ![ダウンロード (4)](https://github.com/user-attachments/assets/e64bf6b4-c8b9-4aac-9c60-fb68881a4983) | ![ダウンロード (3)](https://github.com/user-attachments/assets/d8cfe33a-f360-4cca-a69c-6c821dac88b5) |
| ![ダウンロード (2)](https://github.com/user-attachments/assets/f429e093-6035-4973-9a2a-00f6323edb1a) | ![ダウンロード (1)](https://github.com/user-attachments/assets/f455f97e-8d9f-4542-80d5-b186b38884a0) | ![ダウンロード](https://github.com/user-attachments/assets/bd30f4a8-6658-4226-80c7-35893f7efeb0) |

feat: Enable Grounding in Vertex AI Gemini

---

tools/qrcode/manifest.yaml
tools/qrcode/requirements.txt
tools/qrcode/tools/qrcode_generator.py
tools/qrcode/tools/qrcode_generator.yaml

- update dify_plugin SDK to 0.3.x
- support embedded image in QR code

feat: update qrcode to 0.1.0 to support embedded image and custom file name

---

models/zhipuai/manifest.yaml
models/zhipuai/models/text_embedding/_position.yaml

fix https://github.com/langgenius/dify-official-plugins/issues/1042

fix: zhipu text_embedding  should be a valid list

---

models/gemini/manifest.yaml
models/gemini/models/llm/_position.yaml
models/gemini/models/llm/gemini-2.5-pro-preview-06-05.yaml
models/gemini/requirements.txt

AI Studio: gemini-2.5-pro-preview-06-05

---

models/vertex_ai/manifest.yaml
models/vertex_ai/models/llm/anthropic.claude-3.7-sonnet.yaml
models/vertex_ai/models/llm/anthropic.claude-opus-4.yaml
models/vertex_ai/models/llm/anthropic.claude-sonnet-4.yaml
models/vertex_ai/models/llm/gemini-2.0-flash-lite-001.yaml
models/vertex_ai/models/llm/gemini-2.5-flash-preview-05-20.yaml
models/vertex_ai/models/llm/llm.py

This Pull Request introduces support for several new models and addresses a bug related to the Grounding feature.
Key changes include:
*   **New Model Configurations:**
*   Added configuration files for:
*   Claude Sonnet 4
*   Gemini 2.0 Flash Lite 001
*   Gemini 2.5 Flash Preview 05-20
*   Updated `llm.py` to handle the Claude Sonnet 4 model.
Close https://github.com/langgenius/dify-official-plugins/issues/805
Close https://github.com/langgenius/dify-official-plugins/issues/623
Close https://github.com/langgenius/dify-official-plugins/issues/1018
*   **Grounding Bug Fix:**
*   Resolved an issue where the Grounding feature would only reference the first message in the conversation history. It now correctly utilizes the complete message history.
* …

feat: Add new vertex_ai models and fix Grounding bug

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/llm.py

https://github.com/langgenius/dify/pull/11721

fix: Correct the environment variable name in the error message

---

.github/pull_request_template.md

docs: add description for fixing model parameters for PR template

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/client.py
models/volcengine_maas/models/llm/llm.py
models/volcengine_maas/models/llm/models.py
models/volcengine_maas/provider/volcengine_maas.yaml
models/volcengine_maas/requirements.txt

fix: https://github.com/langgenius/dify-official-plugins/issues/1080

feat: add Doubao-Seed-1.6 series models and support thinking

---

models/zhipuai/manifest.yaml
models/zhipuai/requirements.txt

fix: https://github.com/langgenius/dify-official-plugins/issues/1083

fix: upgrade zhipu sdk

---

models/huggingface_tei/manifest.yaml
models/huggingface_tei/models/helper.py
models/huggingface_tei/models/rerank/rerank.py
models/huggingface_tei/models/text_embedding/text_embedding.py
models/huggingface_tei/provider/huggingface_tei.yaml
models/huggingface_tei/requirements.txt

feat(huggingface_tei): support for setting request timeout and retry count

---

models/openai/manifest.yaml
models/openai/models/llm/_position.yaml
models/openai/models/llm/gpt-4o-audio-preview-2025-06-03.yaml
models/openai/models/llm/llm.py
models/openai/requirements.txt

- Add AudioPromptMessageContent import and processing
- Add gpt-4o-audio-preview-0603 model configuration
- Update token limits from 4096 to 16384 for audio models
- Add modalities parameter handling for audio models
- Update manifest version to 0.0.27
Fixes #1010

fix: Add OpenAI GPT-4o Audio Preview support

---

models/vertex_ai/manifest.yaml
models/vertex_ai/models/llm/gemini-2.5-flash-lite-preview-06-17.yaml
models/vertex_ai/models/llm/gemini-2.5-flash.yaml
models/vertex_ai/models/llm/gemini-2.5-pro.yaml
models/vertex_ai/models/llm/llm.py

feat: Add latest Gemini models to Vertex AI (gemini-2.5-flash,gemini-2.5-pro,gemini-2.5-flash-lite-preview-06-17)

---

models/gemini/manifest.yaml
models/gemini/models/llm/_position.yaml
models/gemini/models/llm/gemini-2.0-flash-preview-image-generation.yaml
models/gemini/models/llm/llm.py

Added the definition file for the ```gemini-2.0-flash-preview-image-generation``` model. This model supports multimodal output, including image generation. Updated _position.yaml to include the new model and modified llm.py logic to enable multimodal output for it.
Incremented the manifest.yaml version to 0.2.5.
To support a new multimodal Gemini model and leverage its image generation and other multimodal capabilities.
Closes #1122

✨ feat(gemini): Add gemini-2.0-flash-preview-image-generation model

---

models/gemini/manifest.yaml
models/gemini/models/llm/_position.yaml
models/gemini/models/llm/gemini-2.5-flash-lite-preview-06-17.yaml
models/gemini/models/llm/gemini-2.5-flash.yaml
models/gemini/models/llm/gemini-2.5-pro.yaml
models/gemini/requirements.txt

✨ AI Studio: add `gemini-2.5-pro`, `gemini-2.5-flash`, `gemini-2.5-flash-lite-preview-06-17`

---

tools/hap/manifest.yaml
tools/hap/requirements.txt
tools/hap/tools/add_worksheet_record.py
tools/hap/tools/delete_worksheet_record.py
tools/hap/tools/get_worksheet_fields.py
tools/hap/tools/get_worksheet_pivot_data.py
tools/hap/tools/get_worksheet_pivot_data.yaml
tools/hap/tools/list_worksheet_records.py
tools/hap/tools/list_worksheet_records.yaml
tools/hap/tools/list_worksheets.py
tools/hap/tools/update_worksheet_record.py

fix: Errors occur when retrieving records and parsing datas

---

models/xinference/manifest.yaml
models/xinference/models/xinference_helper.py
models/xinference/requirements.txt

close https://github.com/langgenius/dify/issues/17183
close https://github.com/langgenius/dify/issues/17765
xinference Interface response
http://192.168.8.96:9997/v1/models/F5-TTS-MLX
```json
{
"model_type": "audio",
"address": "0.0.0.0:53735",
"accelerators": [
],
"model_name": "F5-TTS-MLX",
"model_family": "F5-TTS-MLX",
"model_revision": "7642bb232e3fcacf92c51c786edebb8624da6b93",
"model_ability": [
"text2audio"
],
"replica": 1
}
```
error：
success：

fix: Compatible with the 'text2audio' tts model string in xinference

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/llm/models.py
models/volcengine_maas/requirements.txt

change `Doubao-Seed-1.6 Doubao-Seed-1.6-flash Doubao-Seed-1.6-thinking` support function call

chore: doubao seed 1.6 series support function call

---

tools/searxng/manifest.yaml
tools/searxng/requirements.txt
tools/searxng/tools/searxng_search.py

- fix https://github.com/langgenius/dify-official-plugins/issues/1168
- the empty search results may cause this exception, after change to `yield` response fix this situation
- also upgrade dify_plugin sdk version

fix: searxng get empty search result raise exception

---

models/groq/manifest.yaml
models/groq/models/speech2text/_position.yaml
models/groq/requirements.txt

fix https://github.com/langgenius/dify-official-plugins/issues/1171
after dify 1.5.0,  this plugin's `_position.yaml` is empty,  cause exception
also upgrade dify_plugin sdk version

fix: grop can't install

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/qwen-vl-max.yaml
models/tongyi/models/llm/qwen-vl-plus-0809.yaml
models/tongyi/models/llm/qwen-vl-plus.yaml
models/tongyi/requirements.txt

fix https://github.com/langgenius/dify-official-plugins/issues/1208
also update dify_plugin version

fix: remove duplicated response_format of qwen

---

tools/outlook/manifest.yaml
tools/outlook/requirements.txt
tools/outlook/tools/get_message.py

- There's an error when call get message:
`MessageItem RequestBuilder.get() got an unexpected keyword argument 'select'`
- GraphServiceClient return async coroutine
This PR will fix those errors.
- [x ] I have Bumped Up the Version in Manifest.yaml (Top-Level `Version` Field, Not in Meta Section)

fix outlook plugin get_message

---

models/siliconflow/manifest.yaml
models/siliconflow/models/llm/Internvl2-26b.yaml
models/siliconflow/models/llm/Internvl2-8b.yaml
models/siliconflow/models/llm/_position.yaml
models/siliconflow/models/llm/deepseek-r1-distill-qwen-1.5B.yaml
models/siliconflow/models/llm/internlm2_5-20b-chat.yaml
models/siliconflow/models/llm/internlm2_5-7b-chat.yaml
models/siliconflow/models/llm/meta-llama-3.3-70b-instruct.yaml
models/siliconflow/models/llm/meta-mlama-3.1-8b-instruct.yaml
models/siliconflow/models/tts/fish-speech-1.4.yaml
models/siliconflow/models/tts/fish-speech-1.5.yaml
models/siliconflow/models/tts/gpt-sovits.yaml
models/siliconflow/requirements.txt

- to close https://github.com/langgenius/dify-official-plugins/issues/1216
- deprecated some models follow the offical website
- adjusted the order to prioritize available models at the front
- upgrade dify_plugin sdk version

chore: sort out sillicon models

---

tools/gitlab/manifest.yaml
tools/gitlab/tools/gitlab_files.py

fix https://github.com/langgenius/dify-official-plugins/issues/1235

fix: gitlab fetch_files function missing a parameter

---

models/anthropic/manifest.yaml
models/anthropic/provider/anthropic.py
models/anthropic/requirements.txt

fix https://github.com/langgenius/dify-official-plugins/issues/1224
fix https://github.com/langgenius/dify-official-plugins/issues/1201
but I havn't got a api key for test

fix: claude validate model deprecated

---

tools/tavily/manifest.yaml
tools/tavily/tools/tavily_extract.yaml
tools/tavily/tools/tavily_search.yaml

https://github.com/user-attachments/assets/16eb664b-48bb-4be2-846d-a9079cf9b9ff

chore: improve Tavily parameters readability

---

models/azure_openai/manifest.yaml
models/azure_openai/models/constants.py
models/azure_openai/requirements.txt

Refer to:
https://github.com/langgenius/dify/blob/94a13d7d62067f427d2419a5b8541c2236d95a40/api/core/llm_generator/output_parser/structured_output.py#L128

feat(azure_openai): add support for Dify structured output

---

agent-strategies/cot_agent/manifest.yaml
agent-strategies/cot_agent/requirements.txt
agent-strategies/cot_agent/strategies/function_calling.py

fix: improve agent node tool call readability

---

models/siliconflow/manifest.yaml
models/siliconflow/models/llm/_position.yaml
models/siliconflow/models/llm/glm-41v-9b-thinking.yaml

New model link: https://cloud.siliconflow.cn/sft-5zscin08l0/models?target=THUDM%2FGLM-4.1V-9B-Thinking
Can not test in SaaS Env.

New model in siliconflow: THUDM/GLM-4.1V-9B-Thinking

---

tools/tavily/manifest.yaml
tools/tavily/tools/tavily_search.yaml

chore: make tavily params configurable

---

models/x/manifest.yaml
models/x/models/llm/grok-3-mini.yaml
models/x/models/llm/grok-4-0709.yaml
models/x/requirements.txt

1. fix: remove frequency_penalty parameter from grok-3-mini and grok-3-mini-fast models
2. feat: add grok-4-0709 model configuration

Remove frequency_penalty from grok-3-mini/fast and add grok-4-0709 config

---

models/xinference/manifest.yaml
models/xinference/provider/xinference.yaml

The input type should be text-input, not secret-input.

Fix: Server URL of Xinference plugin is hidden #1264

---

models/openrouter/manifest.yaml
models/openrouter/models/llm/llm.py

To display the ranking of requests sent from dify in Openrouter and increase dify's influence.
[https://openrouter.ai/docs/api-reference/overview#headers](https://openrouter.ai/docs/api-reference/overview#headers)

feat: Add OpenRouter specific headers for rankings on openrouter.ai

---

models/huaweicloud_maas/manifest.yaml
models/huaweicloud_maas/models/llm/deepseek-v3.yaml

Supports toggling response_format parameter for deepseek-v3

feat: add response format parameter for deepseek-v3 in huaweicloud maas

---

models/openai/manifest.yaml
models/openai/models/llm/llm.py
models/openai/models/llm/o3-2025-04-16.yaml
models/openai/models/llm/o3-mini-2025-01-31.yaml
models/openai/models/llm/o3-mini.yaml
models/openai/models/llm/o3-pro-2025-06-10.yaml
models/openai/models/llm/o3-pro.yaml
models/openai/models/llm/o3.yaml
models/openai/models/llm/o4-mini-2025-04-16.yaml
models/openai/models/llm/o4-mini.yaml
models/openai/requirements.txt

Fixes https://github.com/langgenius/dify-official-plugins/issues/1282
Fixes https://github.com/langgenius/dify-official-plugins/issues/878
Now o-series can also use tool calling and streming.
https://github.com/user-attachments/assets/2c89c827-b695-487c-b9cd-68189394b214
https://github.com/user-attachments/assets/8e0d1dee-ce9b-477b-8c51-fd284157d1b6

Fix: refract tool calling for all available models

---

models/groq/manifest.yaml
models/groq/models/llm/_position.yaml
models/groq/models/llm/llama-guard-3-8b.yaml
models/groq/models/llm/llama3-70b-8192.yaml
models/groq/models/llm/llama3-8b-8192.yaml
models/groq/models/llm/moonshotai-kimi-k2-instruct.yaml
models/groq/models/llm/qwen-qwen3-32b.yaml

https://console.groq.com/docs/models

Groq: add `kimi-k2-instruct`, `qwen-32b` and flag outdated models

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/llm/models.py
models/volcengine_maas/provider/volcengine_maas.yaml

feat: add volcengine kimi-k2

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/llm/llm.py
models/volcengine_maas/models/llm/models.py

fix #1345
> **Description:** Added pricing information for all LLM models, which directly affects billing calculations based on token consumption.
> **Description:** Added pricing configurations for existing models.
> **New Version:** 0.0.24

feat(volcengine): Add pricing support

---

agent-strategies/cot_agent/manifest.yaml
agent-strategies/cot_agent/strategies/ReAct.py
agent-strategies/cot_agent/strategies/function_calling.py

Fixes #1340
Fixes https://github.com/langgenius/dify-official-plugins/issues/1336
Fixes https://github.com/langgenius/dify-official-plugins/issues/1335

fix: define LogMetadata locally to resolve ImportError in agent plugin

---

tools/outlook/README.md
tools/outlook/manifest.yaml
tools/outlook/provider/outlook.py
tools/outlook/provider/outlook.yaml
tools/outlook/requirements.txt
tools/outlook/tools/send_draft.py
tools/outlook/tools/send_draft.yaml
tools/outlook/tools/send_message.py
tools/outlook/tools/send_message.yaml

- update _SCOPE to return refresh_token
- add `oauth_refresh_credentials`
- remove unneeded description about Graph API permission settings
Should be `dify_plugin>=0.4.2,<0.5.0`

fix: add OAuth refresh token for Outlook & update README

---

models/aihubmix/manifest.yaml
models/aihubmix/models/llm/anthropic.py
models/aihubmix/requirements.txt

fix(aihubmix): fix logic lost

---

models/zhipuai/manifest.yaml
models/zhipuai/models/llm/_position.yaml
models/zhipuai/models/llm/glm-4.5-air.yaml
models/zhipuai/models/llm/glm-4.5-airx.yaml
models/zhipuai/models/llm/glm-4.5-flash.yaml
models/zhipuai/models/llm/glm-4.5-x.yaml
models/zhipuai/models/llm/glm-4.5.yaml
models/zhipuai/models/llm/llm.py
models/zhipuai/requirements.txt

feat: add glm-4.5 series models

---

models/oci/manifest.yaml
models/oci/provider/oci.py

Fix https://github.com/langgenius/dify-official-plugins/issues/1390
Replaced the authentication model with one supported in more regions to resolve credential validation issues due to regional restrictions.

Fix OCI GenAI credential validation

---

tools/spider/manifest.yaml
tools/spider/spiderApp.py

fix(spider): clearer error handling based on http status codes

---

models/tongyi/manifest.yaml
models/tongyi/models/text_embedding/text_embedding.py

fix https://github.com/langgenius/dify-official-plugins/issues/1407

fix: duplicate import bug

---

models/bedrock/manifest.yaml
models/bedrock/models/llm/llm.py

support inference parameters for model of inference profile

---

tools/azuredalle/manifest.yaml
tools/azuredalle/tools/dalle3.py
tools/azuredalle/tools/dalle3.yaml

close: https://github.com/langgenius/dify-official-plugins/issues/1414

fix: remove parameter n, use default value 1

---

models/anthropic/manifest.yaml
models/anthropic/models/llm/claude-opus-4-1-20250805.yaml

Introduces the claude-opus-4-1-20250805 LLM configuration with detailed parameter rules and features. Updates manifest.yaml version to 0.1.2 to reflect the new model addition.

Add claude-opus-4-1-20250805 model and bump version

---

models/groq/manifest.yaml
models/groq/models/llm/_position.yaml
models/groq/models/llm/openai-gpt-oss-120b.yaml
models/groq/models/llm/openai-gpt-oss-20b.yaml

View in LLM block in workflow
Both 120b and 20b available.
Able to set reasoning level
Works in chat flow

feat: Added openai oss models for Groq

---

models/openai/README.md
models/openai/manifest.yaml
models/openai/models/llm/_position.yaml
models/openai/models/llm/gpt-5-chat-latest.yaml
models/openai/models/llm/gpt-5-mini.yaml
models/openai/models/llm/gpt-5-nano.yaml
models/openai/models/llm/gpt-5.yaml

Includes the latest models released by OpenAI
| Model | Input | Cached input | Output |
| --- | --- | --- | --- |
| gpt-5 | $1.25 | $0.125 | $10.00 |
| gpt-5-mini | $0.25 | $0.025 | $2.00 |
| gpt-5-nano | $0.05 | $0.005 | $0.40 |
| gpt-5-chat-latest | $1.25 | $0.125 | $10.00 |

Add gpt-5 models to OpenAI provider

---

models/azure_openai/manifest.yaml
models/azure_openai/models/constants.py
models/azure_openai/models/llm/llm.py
models/azure_openai/provider/azure_openai.yaml
models/azure_openai/requirements.txt

close: https://github.com/langgenius/dify-official-plugins/issues/1433

feat: azure openai support grok-3 and grok-3-mini

---

models/huaweicloud_maas/manifest.yaml
models/huaweicloud_maas/models/llm/deepseek-r1-0528.yaml
models/huaweicloud_maas/models/llm/deepseek-r1.yaml
models/huaweicloud_maas/models/llm/deepseek-v3.yaml

- [] Dify Version is: , I have Tested My Changes on Local Deployment Dify with a Clean Environment That Matches the Production Configuration.

feat: increase deepseek related model's max context length to 64k tokens for huawei cloud maas provider

---

models/aihubmix/manifest.yaml
models/aihubmix/models/llm/_position.yaml
models/aihubmix/models/llm/anthropic.py
models/aihubmix/models/llm/claude-opus-4-1-20250805.yaml
models/aihubmix/models/llm/gpt-5-chat-latest.yaml
models/aihubmix/models/llm/gpt-5-mini.yaml
models/aihubmix/models/llm/gpt-5-nano.yaml
models/aihubmix/models/llm/gpt-5.yaml
models/aihubmix/models/llm/llm.py

feat(aihubmix): support gpt 5

---

models/azure_openai/manifest.yaml
models/azure_openai/models/constants.py
models/azure_openai/models/llm/llm.py
models/azure_openai/provider/azure_openai.yaml

feat: add gpt-5 series model

---

models/azure_openai/manifest.yaml
models/azure_openai/models/constants.py
models/azure_openai/provider/azure_openai.yaml
models/azure_openai/requirements.txt

close: https://github.com/langgenius/dify-official-plugins/issues/1480

fix: azure GPT-5 add verbosity

---

models/azure_openai/manifest.yaml
models/azure_openai/models/constants.py
models/azure_openai/models/llm/llm.py

feat: azure openai support audio and add gpt-4o-audio-preview model

---

models/azure_ai_studio/manifest.yaml
models/azure_ai_studio/models/rerank/rerank.py

Fixes #695 - Azure AI Studio (Azure AI Foundry) reranker model integration was failing with 404 errors due to incorrect API endpoint paths and missing required request fields for Cohere models.
Adding a Rerank model to the Azure AI Studio plugin successfully adds the model without any issues.
**Testing Details:**
- Successfully tested with Azure AI Foundry deployed Cohere-rerank-v3.5 model
- Verified with curl command that matches the exact API format
- Tested credential validation with JWT token authentication
- Confirmed response parsing for Azure AI Foundry format
**What's Changed:**
- **Added endpoint path handling**: Now automatically appends `/v2/rerank` for Azure AI Foundry Cohere models when needed
- **Fixed request body format**: Changed from `{"inputs": query, "docs": docs}` to …

fix: Azure AI Studio Cohere reranker model integration with v2 API support

---

models/hunyuan/manifest.yaml
models/hunyuan/models/llm/hunyuan-t1-latest.yaml
models/hunyuan/models/llm/hunyuan-turbos-latest.yaml
models/hunyuan/models/llm/hunyuan-turbos-longtext-128k-20250325.yaml

Adding three new hunyuan turbos models to hunyuan provider to support the latest AI models available.
- hunyuan-turbos-latest, support 32K input and 16K output
- hunyuan-t1-latest, support 28K input and 64K output
- hunyuan-turbos-longtext-128k-20250325, support 128K input and 6K output
Official document about these new modes is here: https://cloud.tencent.com/document/product/1729/104753
- hunyuan-turbos-latest
- hunyuan-t1-latest
- hunyuan-turbos-longtext-128k-20250325

feat: add three new models of hunyuan provider

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/_position.yaml
models/tongyi/models/llm/llm.py
models/tongyi/models/llm/qwen-mt-plus.yaml
models/tongyi/models/llm/qwen-mt-turbo.yaml
models/tongyi/requirements.txt

close: https://github.com/langgenius/dify-official-plugins/issues/1532

feat: add qwen-mt models

---

models/gemini/README.md

**UsageMetadata**:
- Fixed: #1363
- Fixed: #1350
- Fixed: #655
**outdated**:
- Closes: #755
- Closes: #758
**ThinkingConfig**:
- Fixed: #1211

Close resolved issues 0821

---

models/gemini/.claude/settings.local.json
models/gemini/.difyignore
models/gemini/manifest.yaml
models/gemini/models/llm/gemini-2.0-flash.yaml
models/gemini/models/llm/gemini-2.5-flash-lite.yaml
models/gemini/models/llm/gemini-2.5-flash.yaml
models/gemini/models/llm/gemini-2.5-pro.yaml
models/gemini/models/llm/llm.py
models/gemini/models/llm/test_feature_compatibility.py

This update introduces significant new capabilities for the Gemini model, focusing on tool use, code execution, and robust feature validation.
*   **Enabled Core Gemini Features:**
*   **Tool Calling:** The model can now interact with external tools and APIs, enabled by setting `tool.enabled` to `true` in the manifest.
*   **Code Execution:** Added a `code_execution` feature, allowing the LLM to execute code for complex tasks. This includes refactored streaming logic to parse `executable_code` and `code_execution_result` from the response.
*   **URL Context:** Introduced support for the `url_context` parameter, allowing URLs to be provided as context to the model.
*   **Implemented Strict Feature Compatibility Validation:**
*   To ensure stability, a new validation layer prevents …

feat(gemini): tool calling

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/llm.py

**Related Issue:** [#1545 - Qwen-VL-Plus model cannot recognize video anomalies, but works fine with images](https://github.com/langgenius/dify-official-plugins/issues/1545)
This PR fixes a critical issue where Qwen-VL-Plus model cannot process video content while image processing works normally. The error message was:
```
Run failed: [tongyi] Error: req_id: ef2f6895d0 PluginInvokeError: {"args": {"description":"[models] Error: not support base64, please set MULTIMODAL_SEND_FORMAT to url"},"error_type":"InvokeError","message":"[models] Error: not support base64, please set MULTIMODAL_SEND_FORMAT to url"}
```
**Root Cause Analysis:**
1. Video processing logic was missing - the code directly threw an error when detecting video content
2. Inconsistent handling between image and video - image …

fix(tongyi): enable video processing for Qwen-VL-Plus model

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/models/llm/llm.py
models/volcengine_maas/models/llm/models.py
models/volcengine_maas/provider/volcengine_maas.yaml

feat: volcengine add deepseek-v3.1

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/deepseek-v3.1.yaml

add: deepseek v3.1

---

models/volcengine_maas/manifest.yaml
models/volcengine_maas/provider/volcengine_maas.yaml

Fix #1551 volc model duplicate deepseek-v3.1 and missing kimi-k2

---

models/openrouter/manifest.yaml
models/openrouter/models/llm/_position.yaml
models/openrouter/models/llm/deepseek-chat-v3.1.yaml
models/openrouter/models/llm/llm.py

related issue : fix https://github.com/langgenius/dify-official-plugins/issues/1576

Fix/openrouter claude vision support issue #1576

---

tools/dify_extractor/manifest.yaml
tools/dify_extractor/tools/dify_extractor.py
tools/dify_extractor/tools/dify_extractor.yaml
tools/dify_extractor/tools/json_extractor.py
tools/dify_extractor/tools/yaml_extractor.py

This PR adds support for JSON and YAML file extraction to the `dify_extractor` tool, expanding its capabilities to handle structured data formats commonly used in configuration files, APIs, and data exchange.
close https://github.com/langgenius/dify/issues/24530
close https://github.com/langgenius/dify/issues/24529
- **`tools/json_extractor.py`**: Implements `JSONExtractor` class for parsing JSON files
- **`tools/yaml_extractor.py`**: Implements `YAMLExtractor` class for parsing YAML files
- **`tools/dify_extractor.py`**: Updated to integrate the new extractors
- **`tools/dify_extractor.yaml`**: Updated configuration to support `.json` and `.yaml`/`.yml` file extensions
- Parses JSON files and converts them to readable Markdown format
- Handles nested objects and arrays with proper …

feat: add JSON and YAML extractors to dify_extractor

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/_position.yaml
models/tongyi/models/llm/qwen-plus-2025-07-28.yaml

close: https://github.com/langgenius/dify-official-plugins/issues/1594

feat: add qwen-plus-2025-07-28 and update qwen-plus-latest

---

models/siliconflow/manifest.yaml
models/siliconflow/models/rerank/qwen3-reranker-0.6b.yaml
models/siliconflow/models/rerank/qwen3-reranker-4b.yaml
models/siliconflow/models/rerank/qwen3-reranker-8b.yaml
models/siliconflow/models/text_embedding/qwen3-embedding-0.6b.yaml
models/siliconflow/models/text_embedding/qwen3-embedding-4b.yaml
models/siliconflow/models/text_embedding/qwen3-embedding-8b.yaml

close: https://github.com/langgenius/dify-official-plugins/issues/1592

feat: add qwen3 embedding and reranker models from siliconflow

---

tools/gitlab/manifest.yaml
tools/gitlab/requirements.txt

fix(gitlab): bump sdk version

---

tools/comfyui/main.py
tools/comfyui/manifest.yaml
tools/comfyui/provider/comfyui.py
tools/comfyui/ruff.toml
tools/comfyui/tools/comfyui_client.py
tools/comfyui/tools/comfyui_workflow.py
tools/comfyui/tools/convert_to_api.py
tools/comfyui/tools/download_by_json.py
tools/comfyui/tools/download_by_url.py
tools/comfyui/tools/download_civitai.py
tools/comfyui/tools/download_huggingface.py
tools/comfyui/tools/image_info.py
tools/comfyui/tools/img2any.py
tools/comfyui/tools/img2img.py
tools/comfyui/tools/img2vid.py
tools/comfyui/tools/list_models.py
tools/comfyui/tools/list_samplers.py
tools/comfyui/tools/model_manager.py
tools/comfyui/tools/quickstart.py
tools/comfyui/tools/run_workflow.py
tools/comfyui/tools/txt2img.py
tools/comfyui/tools/txt2vid.py

* Fix: https://github.com/langgenius/dify-official-plugins/issues/1617
* Refactor: introduce ruff as a formatter with the same style with [Dify's](https://github.com/langgenius/dify/blob/0fe078d25e2ea64d6df473f338b5b93c63b28950/api/.ruff.toml)

fix: ComfyUI 0.2.5

---

models/x/manifest.yaml
models/x/models/llm/grok-2-vision-1212.yaml
models/x/models/llm/grok-3-fast.yaml
models/x/models/llm/grok-3-mini-fast.yaml
models/x/models/llm/grok-code-fast-1-0825.yaml
models/x/provider/x.yaml

- feat(model/x): update model versions and add new model grok-code-fast-1-0825
- fix(model/x): mark multiple grok models as deprecated

Add grok-code-fast-1-0825 model and deprecate multiple grok models

---

datasources/sharepoint_datasource/manifest.yaml

update minimum_dify_versio for sharepoint datasource

fix: update minimum_dify_version for sharepoint datasource

---

extensions/slack_bot/README.md
extensions/slack_bot/endpoints/slack.py
extensions/slack_bot/manifest.yaml
extensions/slack_bot/requirements.txt

Enhanced Slack Bot plugin to support proper markdown formatting in messages. The bot now correctly converts standard markdown to Slack's mrkdwn format and uses proper Block Kit structure for rich message display. This is especially important in the era of LLMs, as many large models use markdown responses.
- use https://github.com/fla9ua/markdown_to_mrkdwn to convert standard markdown syntax to Slack mrkdwn format
- Updated message sending logic to use Block Kit with proper `mrkdwn` text type
- Simplified code by removing complex original blocks manipulation
- Added support for bold, italic, strikethrough, inline code, links, and code blocks formatting
- **Bold**: `**text**` → `*text*` 
- **Italic**: `*text*` → `_text_`
- **Strikethrough**: `~~text~~` → `~text~`
- **Links**: `[text](url)` …

feat(slack_bot): support markdown formatting

---

datasources/dropbox_datasource/datasources/dropbox.yaml
datasources/dropbox_datasource/manifest.yaml
datasources/dropbox_datasource/provider/dropbox.py
datasources/dropbox_datasource/provider/dropbox.yaml
datasources/dropbox_datasource/requirements.txt

dropbox bump to v0.2.0

---

models/tongyi/manifest.yaml
models/tongyi/models/llm/qwen-turbo-2025-07-15.yaml
models/tongyi/models/llm/qwen-turbo-latest.yaml

fix: qwen-turbo-latest support function call

---

models/moonshot/manifest.yaml
models/moonshot/models/llm/kimi-k2-0905-preview.yaml
models/moonshot/models/llm/kimi-k2-turbo-preview.yaml

feat: kimi k2

---

datasources/aws_s3_storage/README.md
datasources/aws_s3_storage/datasources/aws_s3_storage.py
datasources/aws_s3_storage/manifest.yaml

fix(datasource/aws_s3): remove print()

---

tools/qa_chunk/manifest.yaml
tools/qa_chunk/requirements.txt

chore(tools/qa_chunk): remove useless dependencies

---

tools/general_chunk/manifest.yaml
tools/general_chunk/requirements.txt

chore(tools/general_chunk): remove useless dependencies

---

datasources/aws_s3_storage/manifest.yaml
datasources/azure_blob/manifest.yaml
datasources/box_datasource/manifest.yaml
datasources/brightdata_datasource/manifest.yaml
datasources/confluence_datasource/manifest.yaml
datasources/dropbox_datasource/manifest.yaml
datasources/firecrawl_datasource/manifest.yaml
datasources/github/README.md
datasources/github/manifest.yaml
datasources/gitlab_datasource/manifest.yaml
datasources/google_cloud_storage/manifest.yaml
datasources/google_drive/manifest.yaml
datasources/jina_datasource/manifest.yaml
datasources/notion_datasource/manifest.yaml
datasources/onedrive/README.md
datasources/onedrive/manifest.yaml
datasources/sharepoint_datasource/manifest.yaml
datasources/tavily_datasource/manifest.yaml
tools/dify_extractor/manifest.yaml
tools/dify_extractor/provider/dify_extractor.yaml
tools/general_chunk/manifest.yaml
tools/general_chunk/provider/general_chunk.yaml
tools/parent_child_chunk/manifest.yaml
tools/parent_child_chunk/provider/parent_child_chunk.yaml
tools/qa_chunk/manifest.yaml
tools/qa_chunk/provider/qa_chunk.yaml
tools/unstructured/manifest.yaml

- add `rag` tag to knowledge pipeline related plugins
- adjust minimal_dify_version to `1.9.0` for data source plugins

chore: adjust tags and minimal_dify_version for knowledge pipeline plugins

---

models/openai/manifest.yaml
models/openai/models/llm/llm.py

fix: gpt-5 token

---

models/bedrock/manifest.yaml
models/bedrock/models/llm/anthropic-claude.yaml
models/bedrock/models/llm/llm.py
models/bedrock/models/llm/model_ids.py
models/bedrock/models/llm/openai.yaml
models/bedrock/models/llm/qwen.yaml

Support Claude 4.1 Opus, OpenAI GPT OSS(120B,20B), Deepseek V3.1, Qwen(235B, 32B, Coder 480B, Coder 30B)

Support Claude 4.1 Opus, OpenAI GPT OSS(120B,20B), Deepseek V3.1, Qwen

---

tools/dingo/manifest.yaml
tools/dingo/requirements.txt

The dingo plugin fails to install with ModuleNotFoundError: No module named 'dify_plugin' because the essential dify_plugin dependency is missing from requirements.txt.
This commit adds dify_plugin as the first dependency, which is required for the plugin to run in the Dify environment.
Fixes plugin installation failures in both local and cloud Dify instances.

fix: add missing dify_plugin dependency to requirements.txt

---

models/gemini/manifest.yaml
models/gemini/models/llm/_position.yaml
models/gemini/models/llm/gemini-2.5-flash-image-preview.yaml
models/gemini/models/llm/gemini-flash-latest.yaml
models/gemini/models/llm/gemini-flash-lite-latest.yaml

- Added new model configuration for `gemini-flash-latest` 
- Added new model configuration for `gemini-flash-lite-latest` 
- Updated manifest version to 0.5.5 to reflect new model additions
- Updated model list to include both new latest models
- Renamed `gemini-2.5-flash-image-preview` label to 'Nano Banana'

feat(gemini): add `gemini-flash-latest` and `gemini-flash-lite-latest` models

---

models/modelscope/manifest.yaml
models/modelscope/models/llm/_position.yaml
models/modelscope/models/llm/ernie-4.5-vl-28b-a3b-pt.yaml
models/modelscope/models/llm/llm.py
models/modelscope/models/llm/qwen2.5-vl-32B-instruct.yaml
models/modelscope/models/llm/qwen2.5-vl-3B-instruct.yaml
models/modelscope/models/llm/qwen2.5-vl-72B-instruct.yaml
models/modelscope/models/llm/qwen2.5-vl-7B-instruct.yaml
models/modelscope/models/llm/qwen3-vl-235b-a22b-instruct.yaml

- 在 manifest.yaml 中添加 vision: true 权限
- 实现 modelscope.py 中的凭据验证逻辑
- 添加新的视觉模型 qwen3-vl-235b-a22b-instruct
- 更新所有 VL 模型配置以确保正确的 features 标识
- 清理项目缓存文件
这些修改确保 ModelScope 插件完全支持视觉模型功能，符合 Dify 官方模型设计规范。

fix(modelscope): 修复视觉模型支持问题

---

models/siliconflow/manifest.yaml
models/siliconflow/models/llm/deepseek-v3.1-terminus-pro.yaml
models/siliconflow/models/llm/deepseek-v3.1-terminus.yaml

- [] I have Run Comprehensive Tests Relevant to My Changes

feat: siliconflow add DeepSeek-V3.1-Terminus

---

models/bedrock/manifest.yaml
models/bedrock/models/llm/anthropic-claude.yaml
models/bedrock/models/llm/model_ids.py

chore: add claude sonnet 4.5
